/*
    Charles Daffern (Score_Under)'s PKSV - Pokemon ROM script viewer/editor
    Copyright (C) 2007  Charles Daffern

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
#define log(asd,fgh) WriteFile(LogFile,asd,fgh,&read,NULL)
#define aa(x) else if (!strcmp(buf,x))
#define ec() e_c(Script,&i,LogFile)
#define rom(c,s) j=c;WriteFile(RomFile,&j,s,&read,NULL)
#define BASIC(x) rom(x,1)
#define vlog(x) vlogProc(LogFile,x)
void e_c(char*Script,int*ii,HANDLE LogFile)
{
  register unsigned int i=*ii;
  DWORD read;
  while(Script[i+1]==' '){i++;}
  if(Script[i+1]=='\''){while(Script[i+1]!='\n'&&Script[i+1]!=0){i++;}}
  if(Script[i+1]!='\n'){log("Extra characters on line. Ignoring.\r\n",37);}
  while(chr!='\n'){i++;}
  *ii=i;
  return;
}
void vlogProc(HANDLE LogFile,char*x)
{
  DWORD read;
  if (IsVerbose){log(x,strlen(x));}
  return;
}
void RecodeProc(char*script,char*romfn)
{
  HANDLE CurrFile,IncFile,RomFile;
  char*Script;             //Whoops, used the same name for the filename.
                           //Use caps-lock carefully.
  char buf[1024],buf2[1024],buf3[1024];
  void*temp_ptr;
  unsigned int fs,la,fst,i,line,j,k,l,arg1,arg2,arg3,arg4,arg5,arg6;
  DWORD read;
  SetLastError(0);
  CurrFile=CreateFile(script,GENERIC_READ,FILE_SHARE_READ|FILE_SHARE_WRITE|FILE_SHARE_DELETE,NULL,OPEN_EXISTING,FILE_ATTRIBUTE_NORMAL,NULL);
  RomFile=CreateFile(romfn,GENERIC_WRITE,FILE_SHARE_READ|FILE_SHARE_WRITE|FILE_SHARE_DELETE,NULL,OPEN_EXISTING,FILE_ATTRIBUTE_NORMAL,NULL);
  la=GetLastError();
  if(la)
  {
    strcat(romfn,".gba");
    RomFile=CreateFile(romfn,GENERIC_WRITE,FILE_SHARE_READ|FILE_SHARE_WRITE|FILE_SHARE_DELETE,NULL,OPEN_EXISTING,FILE_ATTRIBUTE_NORMAL,NULL);
    la=GetLastError();
  }
  strcat(GlobBuf,"pokeinc.txt");
  IncFile=CreateFile(GlobBuf,GENERIC_READ,FILE_SHARE_READ|FILE_SHARE_WRITE|FILE_SHARE_DELETE,NULL,OPEN_EXISTING,FILE_ATTRIBUTE_NORMAL,NULL);
  if(IncFile==INVALID_HANDLE_VALUE)
  {
    printf(GlobBuf);
    MessageBox(NULL,"The default includes (pokeinc.txt) could not be opened","Error",0x10);
    CloseHandle(CurrFile);
    return;
  }
  if(la)
  {
    FormatMessage(FORMAT_MESSAGE_FROM_SYSTEM,NULL,la,0,buf,1023,NULL);
    MessageBox(NULL,buf,"Error",0x40);
    CloseHandle(IncFile);
    return;
  }
  if(CurrFile!=INVALID_HANDLE_VALUE)
  {
    SetLastError(0);
    fs=GetFileSize(CurrFile,NULL);
    fst=GetFileSize(IncFile,NULL);
    la=GetLastError();
    if(la)
    {
      FormatMessage(FORMAT_MESSAGE_FROM_SYSTEM,NULL,la,0,buf,1023,NULL);
      MessageBox(NULL,buf,"Error",0x40);
      if(strcmp(script,""))CloseHandle(CurrFile);
      CloseHandle(IncFile);
      return;
    }
    Script=GlobalAlloc(GPTR,fs+fst+6);
    if(Script==NULL)
    {
      MessageBox(NULL,"GlobalAlloc() Failed to allocate memory for the script.","Error",0x10);
      if(strcmp(script,""))CloseHandle(CurrFile);
      CloseHandle(IncFile);
      return;
    }
    ZeroMemory(Script,fs+fst+6);
    ReadFile(IncFile,Script,fst,&read,NULL);
    strcat(Script,"\n");
    strcat(Script,"\n");
    ReadFile(CurrFile,(char*)(Script+fst+2),fs,&read,NULL);
    strcat(Script,"\n");
    strcat(Script,"\n");
    LogFile=CreateFile("PokeScrE.log",GENERIC_WRITE,FILE_SHARE_READ|FILE_SHARE_WRITE|FILE_SHARE_DELETE,NULL,CREATE_ALWAYS,FILE_ATTRIBUTE_NORMAL,NULL);
    if(LogFile==NULL)
    {
      MessageBox(NULL,"Failed to open a log.","Error",0x10);
      GlobalFree(Script);
      if(strcmp(script,""))CloseHandle(CurrFile);
      CloseHandle(IncFile);
      return;
    }
    WriteFile(LogFile,"Opened file.\r\n",14,&read,NULL);
    i=0;
    LowerCase(Script);
    RemAll0D(Script);
    while(i<strlen(Script))
    {
      switch(chr) //Behave differently according to char
      {
        case 0:  //E O Script
          return;
        case '\'':
          while(chr!='\n'&&chr!=0)
          {i++;}i--;break;
        case ' ':  //Ignore spaces
        case '\n':
          break;
        default:
          j=0;
          while(chr!=' '&&chr!='\n'&&chr!=0)
          {
            buf[j]=chr;
            i++;
            j++;
          }
          buf[j]=0;
//aa    is just shorthand for  "else if (!strcmp (buf, x))"
//ec    is End Command
//log   is self-explanatory
//rom   writes to rom
//basic is shorthand for rom(x,1)
          if(!strcmp(buf,"#define"))
          {
            vlog("#DEFINE\r\n");
            while(chr==' '){i++;}
            if(chr=='\n'||chr==0)
            {
              log("Premature end to #DEFINE!\r\n",27);
              return;
            }
            j=0;
            while(chr!=' '&&chr!='\n'&&chr!=0)
            {
              buf[j]=chr;
              i++;
              j++;
            }
            buf[j]=0; //Append null
            sprintf(buf2,"   -> %s\r\n",buf);
            vlog(buf2);
            while(chr==' '){i++;} //The same old same old.
            if(chr=='\n'||chr==0)
            {
              log("Premature end to #DEFINE!\r\n",27);
              return;
            }
            k=GetNum("#DEFINE");
            if (!gffs){return;}
            Define(buf,k);
            ec();
          }
          aa("#org")
          {
            vlog("#ORG\r\n");
            k=GetNum("#ORG");
            if(!gffs){return;}
            SetFilePointer(RomFile,k&0x00ffffff,NULL,FILE_BEGIN);
            ec();
          }
          aa("#quiet")
          {
            IsVerbose=0;
            ec();
          }
          aa("#loud")
          {
            IsVerbose=1;
            ec();
          }
          aa("#raw")
          {
            vlog("#RAW\r\n");
            k=GetNum("#RAW");
            if(!gffs){return;}
            BASIC(k);
            if(k>255)
            {
              BASIC(k>>8);
              if(k>65535)
              {
                BASIC(k>>16);
                if(k>16777215)
                {
                  BASIC(k>>24);
                }
              }
            }
            ec();
          }
          aa("end")                 {BASIC(CMD_END);                 ec();} //BASIC() writes 1 byte to ROM
          aa("return")              {BASIC(CMD_RETURN);              ec();}
          aa("nop")                 {BASIC(CMD_NOP0);                ec();}
          aa("nop0")                {BASIC(CMD_NOP0);                ec();}
          aa("nop1")                {BASIC(CMD_NOP1);                ec();}
          aa("checkgender")         {BASIC(CMD_CHECKGENDER);         ec();}
          aa("lockall")             {BASIC(CMD_LOCKALL);             ec();}
          aa("closemsg")            {BASIC(CMD_CLOSEMSG);            ec();}
          aa("faceplayer")          {BASIC(CMD_FACEPLAYER);          ec();}
          aa("lock")                {BASIC(CMD_LOCK);                ec();}
          aa("release")             {BASIC(CMD_RELEASE);             ec();}
          aa("releaseall")          {BASIC(CMD_RELEASEALL);          ec();}
          aa("waitbutton")          {BASIC(CMD_WAITBUTTON);          ec();}
          aa("killscript")          {BASIC(CMD_KILLSCRIPT);          ec();}
          aa("waitfanfare")         {BASIC(CMD_WAITFANFARE);         ec();}
          aa("doweather")           {BASIC(CMD_DOWEATHER);           ec();}
          aa("waitspecial")         {BASIC(CMD_WAITSPECIAL);         ec();}
          aa("showmsg")             {BASIC(CMD_SHOWMSG);             ec();}
          aa("fadedefault")         {BASIC(CMD_FADEDEFAULT);         ec();}
          aa("fadeout")             {BASIC(CMD_FADEOUT);             ec();}
          aa("fadein")              {BASIC(CMD_FADEIN);              ec();}
          aa("countpokemon")        {BASIC(CMD_COUNTPOKEMON);        ec();}
          aa("jumpram")             {BASIC(CMD_JUMPRAM);             ec();}
          aa("hidepokepic")         {BASIC(CMD_HIDEPOKEPIC);         ec();}
          aa("doorchange")          {BASIC(CMD_DOORCHANGE);          ec();}
          aa("msgboxsign")          {BASIC(CMD_MSGBOXSIGN);          ec();}
          aa("msgboxnormal")        {BASIC(CMD_MSGBOXNORMAL);        ec();}
          aa("executeram")          {BASIC(CMD_EXECUTERAM);          ec();}
          aa("lastbattle")          {BASIC(CMD_LASTBATTLE);          ec();}
          aa("cmd_b2")              {BASIC(CMD_B2);                  ec();}
          aa("resetweather")        {BASIC(CMD_RESETWEATHER);        ec();}
          aa("startcontest")        {BASIC(CMD_STARTCONTEST);        ec();}
          aa("choosecontestpokemon"){BASIC(CMD_CHOOSECONTESTPOKEMON);ec();}
          aa("lasttrainerbattle")   {BASIC(CMD_LASTTRAINERBATTLE);   ec();}
          aa("endtrainerbattle")    {BASIC(CMD_ENDTRAINERBATTLE);    ec();}
          aa("endtrainerbattle2")   {BASIC(CMD_ENDTRAINERBATTLE2);   ec();}
          aa("fadedefault")         {BASIC(CMD_FADEDEFAULT);         ec();}
          aa("resetvars")           {BASIC(CMD_RESETVARS);           ec();}
          aa("cmd_2d")              {BASIC(CMD_2D);                  ec();}
          aa("startwireless")       {BASIC(CMD_STARTWIRELESS);       ec();}
          aa("showpokepic")
          {
            vlog("SHOWPOKEPIC\r\n");
            arg1=GetNum("SHOWPOKEPIC");
            if(!gffs){return;}
            arg2=GetNum("SHOWPOKEPIC");
            if(!gffs){return;}
            arg3=GetNum("SHOWPOKEPIC");
            if(!gffs){return;}
            BASIC(CMD_SHOWPOKEPIC);
            rom(arg1,2);
            rom(arg2,1);
            rom(arg3,1);
            ec();
          }
          aa("storeitems")
          {
            vlog("STOREITEMS\r\n");
            arg1=GetNum("STOREITEMS");
            if(!gffs){return;}
            arg2=GetNum("STOREITEMS");
            if(!gffs){return;}
            arg3=GetNum("STOREITEMS");
            if(!gffs){return;}
            BASIC(CMD_STOREITEMS);
            rom(arg1,1);
            rom(arg2,2);
            rom(arg3,2);
            ec();
          }
          aa("setpokemonpp")
          {
            vlog("SETPOKEMONPP\r\n");
            arg1=GetNum("SETPOKEMONPP");
            if(!gffs){return;}
            arg2=GetNum("SETPOKEMONPP");
            if(!gffs){return;}
            arg3=GetNum("SETPOKEMONPP");
            if(!gffs){return;}
            BASIC(CMD_SETPOKEMONPP);
            rom(arg1,1);
            rom(arg2,1);
            rom(arg3,2);
            ec();
          }
          aa("storepokemonvar")
          {
            vlog("STOREPOKEMONVAR\r\n");
            arg1=GetNum("STOREPOKEMONVAR");
            if(!gffs){return;}
            arg2=GetNum("STOREPOKEMONVAR");
            if(!gffs){return;}
            BASIC(CMD_STOREPOKEMONVAR);
            rom(arg1,1);
            rom(arg2,2);
            ec();
          }
          aa("storefirstpokemon")
          {
            vlog("STOREFIRSTPOKEMON\r\n");
            arg1=GetNum("STOREFIRSTPOKEMON");
            if(!gffs){return;}
            BASIC(CMD_STOREFIRSTPOKEMON);
            rom(arg1,1);
            ec();
          }
          aa("setcatchlocation")
          {
            vlog("SETCATCHLOCATION\r\n");
            arg1=GetNum("SETCATCHLOCATION");
            if(!gffs){return;}
            arg2=GetNum("SETCATCHLOCATION");
            if(!gffs){return;}
            BASIC(CMD_SETCATCHLOCATION);
            rom(arg1,2);
            rom(arg2,1);
            ec();
          }
          aa("cmd_8a")
          {
            vlog("CMD_8A\r\n");
            arg1=GetNum("CMD_8A");
            if(!gffs){return;}
            arg2=GetNum("CMD_8A");
            if(!gffs){return;}
            arg3=GetNum("CMD_8A");
            if(!gffs){return;}
            BASIC(CMD_8A);
            rom(arg1,1);
            rom(arg2,1);
            rom(arg3,1);
            ec();
          }
          aa("setdoorclosed")
          {
            vlog("SETDOORCLOSED\r\n");
            arg1=GetNum("SETDOORCLOSED");
            if(!gffs){return;}
            arg2=GetNum("SETDOORCLOSED");
            if(!gffs){return;}
            BASIC(CMD_SETDOORCLOSED);
            rom(arg1,2);
            rom(arg2,2);
            ec();
          }
          aa("setdoorclosedstatic")
          {
            vlog("SETDOORCLOSEDSTATIC\r\n");
            arg1=GetNum("SETDOORCLOSEDSTATIC");
            if(!gffs){return;}
            arg2=GetNum("SETDOORCLOSEDSTATIC");
            if(!gffs){return;}
            BASIC(CMD_SETDOORCLOSEDSTATIC);
            rom(arg1,2);
            rom(arg2,2);
            ec();
          }
          aa("warpteleport2")
          {
            vlog("WARPTELEPORT2\r\n");
            arg1=GetNum("WARPTELEPORT2");
            if(!gffs){return;}
            arg2=GetNum("WARPTELEPORT2");
            if(!gffs){return;}
            arg3=GetNum("WARPTELEPORT2");
            if(!gffs){return;}
            if(mode==FIRE_RED)
            {
              arg4=GetNum("WARPTELEPORT2");
              if(!gffs){return;}
              arg5=GetNum("WARPTELEPORT2");
              if(!gffs){return;}
            }
            BASIC(CMD_WARPTELEPORT2);
            rom(arg1,1);
            rom(arg2,1);
            rom(arg3,1);
            if(mode==FIRE_RED)
            {
              rom(arg4,2);
              rom(arg5,2);
            }
            ec();
          }
          aa("warp6")
          {
            vlog("WARP6\r\n");
            arg1=GetNum("WARP6");
            if(!gffs){return;}
            arg2=GetNum("WARP6");
            if(!gffs){return;}
            arg3=GetNum("WARP6");
            if(!gffs){return;}
            if(mode==FIRE_RED)
            {
              arg4=GetNum("WARP6");
              if(!gffs){return;}
              arg5=GetNum("WARP6");
              if(!gffs){return;}
            }
            BASIC(CMD_WARP6);
            rom(arg1,1);
            rom(arg2,1);
            rom(arg3,1);
            if(mode==FIRE_RED)
            {
              rom(arg4,2);
              rom(arg5,2);
            }
            ec();
          }
          aa("warpmuted")
          {
            vlog("WARPMUTED\r\n");
            arg1=GetNum("WARPMUTED");
            if(!gffs){return;}
            arg2=GetNum("WARPMUTED");
            if(!gffs){return;}
            arg3=GetNum("WARPMUTED");
            if(!gffs){return;}
            if(mode==FIRE_RED)
            {
              arg4=GetNum("WARPMUTED");
              if(!gffs){return;}
              arg5=GetNum("WARPMUTED");
              if(!gffs){return;}
            }
            BASIC(CMD_WARPMUTED);
            rom(arg1,1);
            rom(arg2,1);
            rom(arg3,1);
            if(mode==FIRE_RED)
            {
              rom(arg4,2);
              rom(arg5,2);
            }
            ec();
          }
          aa("warpwalking")
          {
            vlog("WARPWALKING\r\n");
            arg1=GetNum("WARPWALKING");
            if(!gffs){return;}
            arg2=GetNum("WARPWALKING");
            if(!gffs){return;}
            arg3=GetNum("WARPWALKING");
            if(!gffs){return;}
            if(mode==FIRE_RED)
            {
              arg4=GetNum("WARPWALKING");
              if(!gffs){return;}
              arg5=GetNum("WARPWALKING");
              if(!gffs){return;}
            }
            BASIC(CMD_WARPWALKING);
            rom(arg1,1);
            rom(arg2,1);
            rom(arg3,1);
            if(mode==FIRE_RED)
            {
              rom(arg4,2);
              rom(arg5,2);
            }
            ec();
          }
          aa("warpteleport")
          {
            vlog("WARPTELEPORT\r\n");
            arg1=GetNum("WARPTELEPORT");
            if(!gffs){return;}
            arg2=GetNum("WARPTELEPORT");
            if(!gffs){return;}
            arg3=GetNum("WARPTELEPORT");
            if(!gffs){return;}
            if(mode==FIRE_RED)
            {
              arg4=GetNum("WARPTELEPORT");
              if(!gffs){return;}
              arg5=GetNum("WARPTELEPORT");
              if(!gffs){return;}
            }
            BASIC(CMD_WARPTELEPORT);
            rom(arg1,1);
            rom(arg2,1);
            rom(arg3,1);
            if(mode==FIRE_RED)
            {
              rom(arg4,2);
              rom(arg5,2);
            }
            ec();
          }
          aa("warp3")
          {
            vlog("WARP3\r\n");
            arg1=GetNum("WARP3");
            if(!gffs){return;}
            arg2=GetNum("WARP3");
            if(!gffs){return;}
            arg3=GetNum("WARP3");
            if(!gffs){return;}
            if(mode==FIRE_RED)
            {
              arg4=GetNum("WARP3");
              if(!gffs){return;}
              arg5=GetNum("WARP3");
              if(!gffs){return;}
            }
            BASIC(CMD_WARP3);
            rom(arg1,1);
            rom(arg2,1);
            rom(arg3,1);
            if(mode==FIRE_RED)
            {
              rom(arg4,2);
              rom(arg5,2);
            }
            ec();
          }
          aa("warp4")
          {
            vlog("WARP4\r\n");
            arg1=GetNum("WARP4");
            if(!gffs){return;}
            arg2=GetNum("WARP4");
            if(!gffs){return;}
            arg3=GetNum("WARP4");
            if(!gffs){return;}
            if(mode==FIRE_RED)
            {
              arg4=GetNum("WARP4");
              if(!gffs){return;}
              arg5=GetNum("WARP4");
              if(!gffs){return;}
            }
            BASIC(CMD_WARP4);
            rom(arg1,1);
            rom(arg2,1);
            rom(arg3,1);
            if(mode==FIRE_RED)
            {
              rom(arg4,2);
              rom(arg5,2);
            }
            ec();
          }
          aa("warp5")
          {
            vlog("WARP5\r\n");
            arg1=GetNum("WARP5");
            if(!gffs){return;}
            arg2=GetNum("WARP5");
            if(!gffs){return;}
            arg3=GetNum("WARP5");
            if(!gffs){return;}
            if(mode==FIRE_RED)
            {
              arg4=GetNum("WARP5");
              if(!gffs){return;}
              arg5=GetNum("WARP5");
              if(!gffs){return;}
            }
            BASIC(CMD_WARP4);
            rom(arg1,1);
            rom(arg2,1);
            rom(arg3,1);
            if(mode==FIRE_RED)
            {
              rom(arg4,2);
              rom(arg5,2);
            }
            ec();
          }
          aa("warpelevator")
          {
            vlog("WARPELEVATOR\r\n");
            arg1=GetNum("WARPELEVATOR");
            if(!gffs){return;}
            arg2=GetNum("WARPELEVATOR");
            if(!gffs){return;}
            arg3=GetNum("WARPELEVATOR");
            if(!gffs){return;}
            if(mode==FIRE_RED)
            {
              arg4=GetNum("WARPELEVATOR");
              if(!gffs){return;}
              arg5=GetNum("WARPELEVATOR");
              if(!gffs){return;}
            }
            BASIC(CMD_WARPELEVATOR);
            rom(arg1,1);
            rom(arg2,1);
            rom(arg3,1);
            if(mode==FIRE_RED)
            {
              rom(arg4,2);
              rom(arg5,2);
            }
            ec();
          }
          aa("setdooropened")
          {
            vlog("SETDOOROPENED\r\n");
            arg1=GetNum("SETDOOROPENED");
            if(!gffs){return;}
            arg2=GetNum("SETDOOROPENED");
            if(!gffs){return;}
            BASIC(CMD_SETDOOROPENED);
            rom(arg1,2);
            rom(arg2,2);
            ec();
          }
          aa("getplayerxy")
          {
            vlog("GETPLAYERXY\r\n");
            arg1=GetNum("GETPLAYERXY");
            if(!gffs){return;}
            arg2=GetNum("GETPLAYERXY");
            if(!gffs){return;}
            BASIC(CMD_GETPLAYERXY);
            rom(arg1,2);
            rom(arg2,2);
            ec();
          }
          aa("setdooropenedstatic")
          {
            vlog("SETDOOROPENEDSTATIC\r\n");
            arg1=GetNum("SETDOOROPENEDSTATIC");
            if(!gffs){return;}
            arg2=GetNum("SETDOOROPENEDSTATIC");
            if(!gffs){return;}
            BASIC(CMD_SETDOOROPENEDSTATIC);
            rom(arg1,2);
            rom(arg2,2);
            ec();
          }
          aa("falldownhole")
          {
            vlog("FALLDOWNHOLE\r\n");
            arg1=GetNum("FALLDOWNHOLE");
            if(!gffs){return;}
            arg2=GetNum("FALLDOWNHOLE");
            if(!gffs){return;}
            BASIC(CMD_FALLDOWNHOLE);
            rom(arg1,1);
            rom(arg2,1);
            ec();
          }
          aa("comparehiddenvar")
          {
            vlog("COMPAREHIDDENVAR\r\n");
            arg1=GetNum("COMPAREHIDDENVAR");
            if(!gffs){return;}
            arg2=GetNum("COMPAREHIDDENVAR");
            if(!gffs){return;}
            BASIC(CMD_COMPAREHIDDENVAR);
            rom(arg1,1);
            rom(arg2,2);
            ec();
          }
          aa("updatecoins")
          {
            vlog("UPDATECOINS\r\n");
            arg1=GetNum("UPDATECOINS");
            if(!gffs){return;}
            arg2=GetNum("UPDATECOINS");
            if(!gffs){return;}
            BASIC(CMD_UPDATECOINS);
            rom(arg1,1);
            rom(arg2,1);
            ec();
          }
          aa("doanimation")
          {
            vlog("DOANIMATION\r\n");
            arg1=GetNum("DOANIMATION");
            if(!gffs){return;}
            BASIC(CMD_DOANIMATION);
            rom(arg1,2);
            ec();
          }
          aa("checkobedience")
          {
            vlog("CHECKOBEDIENCE\r\n");
            arg1=GetNum("CHECKOBEDIENCE");
            if(!gffs){return;}
            BASIC(CMD_CHECKOBEDIENCE);
            rom(arg1,2);
            ec();
          }
          aa("setobedience")
          {
            vlog("SETOBEDIENCE\r\n");
            arg1=GetNum("SETOBEDIENCE");
            if(!gffs){return;}
            BASIC(CMD_SETOBEDIENCE);
            rom(arg1,2);
            ec();
          }
          aa("checkanimation")
          {
            vlog("CHECKANIMATION\r\n");
            arg1=GetNum("CHECKANIMATION");
            if(!gffs){return;}
            BASIC(CMD_CHECKANIMATION);
            rom(arg1,2);
            ec();
          }
          aa("msgbox")
          {
            vlog("MSGBOX\r\n");
            arg1=GetNum("MSGBOX");
            if(!gffs){return;}
            if((arg1&0xff000000)==0)
            {
              arg1|=0x08000000;
              sprintf(buf3,"   -> Converted to 0x%x\r\n",arg1);
              vlog(buf3);
            }
            BASIC(CMD_MSGBOX);
            BASIC(0);
            rom(arg1,4);
            ec();
          }
          aa("msgbox2")
          {
            vlog("MSGBOX2\r\n");
            arg1=GetNum("MSGBOX2");
            if(!gffs){return;}
            if((arg1&0xff000000)==0)
            {
              arg1|=0x08000000;
              sprintf(buf3,"   -> Converted to 0x%x\r\n",arg1);
              vlog(buf3);
            }
            BASIC(CMD_MSGBOX2);
            BASIC(0);
            rom(arg1,4);
            ec();
          }
          aa("loadpointer")
          {
            vlog("LOADPOINTER\r\n");
            arg1=GetNum("LOADPOINTER");
            if(!gffs){return;}
            arg2=GetNum("LOADPOINTER");
            if(!gffs){return;}
            if((arg2&0xff000000)==0)
            {
              arg2|=0x08000000;
              sprintf(buf3,"   -> Converted to 0x%x\r\n",arg2);
              vlog(buf3);
            }
            BASIC(CMD_MSGBOX);
            BASIC(arg1);
            rom(arg2,4);
            ec();
          }
          aa("call")
          {
            vlog("CALL\r\n");
            arg1=GetNum("CALL");
            if(!gffs){return;}
            if((arg1&0xff000000)==0)
            {
              arg1|=0x08000000;
              sprintf(buf3,"   -> Converted to 0x%x\r\n",arg1);
              vlog(buf3);
            }
            BASIC(CMD_CALL);
            rom(arg1,4);
            ec();
          }
          aa("jump")
          {
            vlog("JUMP\r\n");
            arg1=GetNum("JUMP");
            if(!gffs){return;}
            if((arg1&0xff000000)==0)
            {
              arg1|=0x08000000;
              sprintf(buf3,"   -> Converted to 0x%x\r\n",arg1);
              vlog(buf3);
            }
            BASIC(CMD_JUMP);
            rom(arg1,4);
            ec();
          }
          aa("setbyte")
          {
            vlog("SETBYTE\r\n");
            arg1=GetNum("SETBYTE");
            if(!gffs){return;}
            BASIC(CMD_SETBYTE);
            BASIC(arg1);
            ec();
          }
          aa("callstd")
          {
            vlog("CALLSTD\r\n");
            arg1=GetNum("CALLSTD");
            if(!gffs){return;}
            BASIC(CMD_CALLSTD);
            BASIC(arg1);
            ec();
          }
          aa("boxset")
          {
            vlog("BOXSET\r\n");
            arg1=GetNum("BOXSET");
            if(!gffs){return;}
            BASIC(CMD_CALLSTD);
            BASIC(arg1);
            ec();
          }
          aa("random")
          {
            vlog("RANDOM\r\n");
            arg1=GetNum("RANDOM");
            if(!gffs){return;}
            BASIC(CMD_RANDOM);
            rom(arg1,2);
            ec();
          }
          aa("spriteface")
          {
            vlog("SPRITEFACE\r\n");
            arg1=GetNum("SPRITEFACE");
            if(!gffs){return;}
            arg2=GetNum("SPRITEFACE");
            if(!gffs){return;}
            BASIC(CMD_SPRITEFACE);
            rom(arg1,2);
            rom(arg2,1);
            ec();
          }
          aa("sethealingplace")
          {
            vlog("SETHEALINGPLACE\r\n");
            arg1=GetNum("SETHEALINGPLACE");
            if(!gffs){return;}
            BASIC(CMD_SETHEALINGPLACE);
            rom(arg1,2);
            ec();
          }
          aa("jumpstd")
          {
            vlog("JUMPSTD\r\n");
            arg1=GetNum("JUMPSTD");
            if(!gffs){return;}
            BASIC(CMD_JUMPSTD);
            BASIC(arg1);
            ec();
          }
          aa("if")
          {
            vlog("IF\r\n");
            arg1=GetNum("IF");
            if(!gffs){return;}
            while(chr==' '){i++;}
            j=0;
            while(chr!=' ')
            {
              buf[j]=chr;
              i++;
              j++;
            }
            buf[j]=0;
            if(!strcmp(buf,"jump")||!strcmp(buf,"goto"))
            {
              vlog("   -> JUMP\r\n");
              arg2=GetNum("IF (JUMP)");
              if(!gffs){return;}
              if((arg2&0xff000000)==0)
              {
                arg2|=0x08000000;
                sprintf(buf3,"   -> Converted to 0x%x\r\n",arg2);
                vlog(buf3);
              }
              BASIC(CMD_JUMPIF);
              BASIC(arg1);
              rom(arg2,4);
            }
            else if(!strcmp(buf,"call"))
            {
              vlog("   -> CALL\r\n");
              arg2=GetNum("IF (CALL)");
              if(!gffs){return;}
              if((arg2&0xff000000)==0)
              {
                arg2|=0x08000000;
                sprintf(buf3,"   -> Converted to 0x%x\r\n",arg2);
                vlog(buf3);
              }
              BASIC(CMD_CALLIF);
              BASIC(arg1);
              rom(arg2,4);
            }
            else if(!strcmp(buf,"callstd"))
            {
              vlog("   -> CALLSTD\r\n");
              arg2=GetNum("IF (CALLSTD)");
              if(!gffs){return;}
              BASIC(CMD_CALLSTDIF);
              BASIC(arg1);
              rom(arg2,1);
            }
            else if(!strcmp(buf,"jumpstd"))
            {
              vlog("   -> JUMPSTD\r\n");
              arg2=GetNum("IF (JUMPSTD)");
              if(!gffs){return;}
              BASIC(CMD_JUMPSTDIF);
              BASIC(arg1);
              rom(arg2,1);
            }
            else
            {
              log("IF was not correctly used. Use with jump, call, callstd and jumpstd.\r\n",58);
              return;
            }
            ec();
          }
          aa("writebytetooffset")
          {
            vlog("   -> WRITEBYTETOOFFSET\r\n");
            arg1=GetNum("WRITEBYTETOOFFSET");
            if(!gffs){return;}
            arg2=GetNum("WRITEBYTETOOFFSET");
            if(!gffs){return;}
            BASIC(CMD_WRITEBYTETOOFFSET);
            rom(arg1,1);
            rom(arg2,4);
            ec();
          }
          aa("loadbytefrompointer")
          {
            vlog("   -> LOADBYTEFROMPOINTER\r\n");
            arg1=GetNum("LOADBYTEFROMPOINTER");
            if(!gffs){return;}
            arg2=GetNum("LOADBYTEFROMPOINTER");
            if(!gffs){return;}
            BASIC(CMD_LOADBYTEFROMPOINTER);
            rom(arg1,1);
            rom(arg2,4);
            ec();
          }
          aa("special")
          {
            vlog("SPECIAL\r\n");
            arg1=GetNum("SPECIAL");
            if(!gffs){return;}
            BASIC(CMD_SPECIAL);
            rom(arg1,2);
            ec();
          }
          aa("setworldmapflag")
          {
            vlog("setworldmapflag\r\n");
            arg1=GetNum("setworldmapflag");
            if(!gffs){return;}
            BASIC(CMD_SETWORLDMAPFLAG);
            rom(arg1,2);
            ec();
          }
          aa("special2")
          {
            vlog("SPECIAL2\r\n");
            arg1=GetNum("SPECIAL2");
            if(!gffs){return;}
            arg2=GetNum("SPECIAL2");
            if(!gffs){return;}
            BASIC(CMD_SPECIAL2);
            rom(arg1,2);
            rom(arg2,2);
            ec();
          }
          aa("compare")
          {
            vlog("COMPARE\r\n");
            arg1=GetNum("COMPARE");
            if(!gffs){return;}
            arg2=GetNum("COMPARE");
            if(!gffs){return;}
            BASIC(CMD_COMPARE);
            rom(arg1,2);
            rom(arg2,2);
            ec();
          }
          aa("copyvar")
          {
            vlog("COPYVAR\r\n");
            arg1=GetNum("COPYVAR");
            if(!gffs){return;}
            arg2=GetNum("COPYVAR");
            if(!gffs){return;}
            BASIC(CMD_COPYVAR);
            rom(arg1,2);
            rom(arg2,2);
            ec();
          }
          aa("copyvarifnotzero")
          {
            vlog("COPYVARIFNOTZERO\r\n");
            arg1=GetNum("COPYVARIFNOTZERO");
            if(!gffs){return;}
            arg2=GetNum("COPYVARIFNOTZERO");
            if(!gffs){return;}
            BASIC(CMD_COPYVARIFNOTZERO);
            rom(arg1,2);
            rom(arg2,2);
            ec();
          }
          aa("message")
          {
            vlog("MESSAGE\r\n");
            arg1=GetNum("MESSAGE");
            if(!gffs){return;}
            BASIC(CMD_MESSAGE);
            if((arg1&0xff000000)==0)
            {
              arg1|=0x08000000;
              sprintf(buf3,"   -> Converted to 0x%x\r\n",arg1);
              vlog(buf3);
            }
            rom(arg1,4);
            ec();
          }
          aa("copyscriptbanks")
          {
            vlog("COPYSCRIPTBANKS\r\n");
            arg1=GetNum("COPYSCRIPTBANKS");
            if(!gffs){return;}
            arg2=GetNum("COPYSCRIPTBANKS");
            if(!gffs){return;}
            BASIC(CMD_COPYSCRIPTBANKS);
            rom(arg1,1);
            rom(arg2,1);
            ec();
          }
          aa("copybyte")
          {
            vlog("COPYBYTE\r\n");
            arg1=GetNum("COPYBYTE");
            if(!gffs){return;}
            arg2=GetNum("COPYBYTE");
            if(!gffs){return;}
            BASIC(CMD_COPYBYTE);
            rom(arg1,4);
            rom(arg2,4);
            ec();
          }
          aa("setvar")
          {
            vlog("SETVAR\r\n");
            arg1=GetNum("SETVAR");
            if(!gffs){return;}
            arg2=GetNum("SETVAR");
            if(!gffs){return;}
            BASIC(CMD_SETVAR);
            rom(arg1,2);
            rom(arg2,2);
            ec();
          }
          aa("comparevartobyte")
          {
            vlog("COMPAREVARTOBYTE\r\n");
            arg1=GetNum("COMPAREVARTOBYTE");
            if(!gffs){return;}
            arg2=GetNum("COMPAREVARTOBYTE");
            if(!gffs){return;}
            BASIC(CMD_COMPAREVARTOBYTE);
            rom(arg1,2);
            rom(arg2,1);
            ec();
          }
          aa("comparevartofarbyte")
          {
            vlog("COMPAREVARTOFARBYTE\r\n");
            arg1=GetNum("COMPAREVARTOFARBYTE");
            if(!gffs){return;}
            arg2=GetNum("COMPAREVARTOFARBYTE");
            if(!gffs){return;}
            BASIC(CMD_COMPAREVARTOFARBYTE);
            rom(arg1,2);
            rom(arg2,4);
            ec();
          }
          aa("comparefarbytetovar")
          {
            vlog("COMPAREFARBYTETOVAR\r\n");
            arg1=GetNum("COMPAREFARBYTETOVAR");
            if(!gffs){return;}
            arg2=GetNum("COMPAREFARBYTETOVAR");
            if(!gffs){return;}
            BASIC(CMD_COMPAREFARBYTETOVAR);
            rom(arg1,4);
            rom(arg2,2);
            ec();
          }
          aa("comparefarbytetobyte")
          {
            vlog("COMPAREFARBYTETOBYTE\r\n");
            arg1=GetNum("COMPAREFARBYTETOBYTE");
            if(!gffs){return;}
            arg2=GetNum("COMPAREFARBYTETOBYTE");
            if(!gffs){return;}
            BASIC(CMD_COMPAREFARBYTETOBYTE);
            rom(arg1,4);
            rom(arg2,1);
            ec();
          }
          aa("comparefarbytetofarbyte")
          {
            vlog("COMPAREFARBYTETOFARBYTE\r\n");
            arg1=GetNum("COMPAREFARBYTETOFARBYTE");
            if(!gffs){return;}
            arg2=GetNum("COMPAREFARBYTETOFARBYTE");
            if(!gffs){return;}
            BASIC(CMD_COMPAREFARBYTETOFARBYTE);
            rom(arg1,4);
            rom(arg2,4);
            ec();
          }
          aa("fadescreen")
          {
            vlog("FADESCREEN\r\n");
            arg1=GetNum("FADESCREEN");
            if(!gffs){return;}
            BASIC(CMD_FADESCREEN);
            rom(arg1,1);
            ec();
          }
          aa("fadescreendelay")
          {
            vlog("FADESCREENDELAY\r\n");
            arg1=GetNum("FADESCREENDELAY");
            if(!gffs){return;}
            arg2=GetNum("FADESCREENDELAY");
            if(!gffs){return;}
            BASIC(CMD_FADESCREENDELAY);
            rom(arg1,1);
            rom(arg2,1);
            ec();
          }
          aa("callasm")
          {
            vlog("CALLASM\r\n");
            arg1=GetNum("CALLASM");
            if(!gffs){return;}
            BASIC(CMD_CALLASM);
            if((arg1&0xff000000)==0)
            {
              arg1|=0x08000000;
              sprintf(buf3,"   -> Converted to 0x%x\r\n",arg1);
              vlog(buf3);
            }
            rom(arg1,4);
            ec();
          }
          aa("callasm2")
          {
            vlog("CALLASM2\r\n");
            arg1=GetNum("CALLASM2");
            if(!gffs){return;}
            BASIC(CMD_CALLASM2);
            if((arg1&0xff000000)==0)
            {
              arg1|=0x08000000;
              sprintf(buf3,"   -> Converted to 0x%x\r\n",arg1);
              vlog(buf3);
            }
            rom(arg1,4);
            ec();
          }
          aa("pause")
          {
            vlog("PAUSE\r\n");
            arg1=GetNum("PAUSE");
            if(!gffs){return;}
            BASIC(CMD_PAUSE);
            rom(arg1,2);
            ec();
          }
          aa("setflag")
          {
            vlog("SETFLAG\r\n");
            arg1=GetNum("SETFLAG");
            if(!gffs){return;}
            BASIC(CMD_SETFLAG);
            rom(arg1,2);
            ec();
          }
          aa("clearflag")
          {
            vlog("CLEARFLAG\r\n");
            arg1=GetNum("CLEARFLAG");
            if(!gffs){return;}
            BASIC(CMD_CLEARFLAG);
            rom(arg1,2);
            ec();
          }
          aa("checkflag")
          {
            vlog("CHECKFLAG\r\n");
            arg1=GetNum("CHECKFLAG");
            if(!gffs){return;}
            BASIC(CMD_CHECKFLAG);
            rom(arg1,2);
            ec();
          }
          aa("sound")
          {
            vlog("SOUND\r\n");
            arg1=GetNum("SOUND");
            if(!gffs){return;}
            BASIC(CMD_SOUND);
            rom(arg1,2);
            ec();
          }
          aa("waitcry")
          {
            vlog("WAITCRY\r\n");
            BASIC(CMD_WAITCRY);
            ec();
          }
          aa("cry")
          {
            vlog("CRY\r\n");
            arg1=GetNum("CRY");
            if(!gffs){return;}
            arg2=GetNum("CRY");
            if(!gffs){return;}
            if(mode==FIRE_RED)
              {BASIC(CMD_CRYFR);rom(arg1,2);}
            else
              {BASIC(CMD_CRY);rom(arg1,1);}
            rom(arg2,2);
            ec();
          }
          aa("checksound")
          {
            vlog("CHECKSOUND\r\n");
            BASIC(CMD_CRY);
            ec();
          }
          aa("fanfare")
          {
            vlog("FANFARE\r\n");
            arg1=GetNum("FANFARE");
            if(!gffs){return;}
            BASIC(CMD_FANFARE);
            rom(arg1,2);
            ec();
          }
          aa("playsound")
          {
            vlog("PLAYSOUND\r\n");
            arg1=GetNum("PLAYSOUND");
            if(!gffs){return;}
            if(mode==FIRE_RED)
            {
              arg1=GetNum("PLAYSOUND");
              if(!gffs){return;}
            }
            BASIC(CMD_PLAYSOUND);
            rom(arg1,2);
            if(mode==FIRE_RED)
            {
              rom(arg2,1);
            }
            ec();
          }
          aa("fadesound")
          {
            vlog("FADESOUND\r\n");
            arg1=GetNum("FADESOUND");
            if(!gffs){return;}
            BASIC(CMD_FADEDEFAULT);
            rom(arg1,2);
            ec();
          }
          aa("fadesong")
          {
            vlog("FADESONG\r\n");
            arg1=GetNum("FADESONG");
            if(!gffs){return;}
            BASIC(CMD_FADESONG);
            rom(arg1,2);
            ec();
          }
          aa("playsong")
          {
            vlog("PLAYSONG\r\n");
            arg1=GetNum("PLAYSONG");
            if(!gffs){return;}
            BASIC(CMD_PLAYSONG);
            rom(arg1,2);
            ec();
          }
          aa("fadedefault")
          {
            vlog("FADEDEFAULT\r\n");
            arg1=GetNum("FADEDEFAULT");
            if(!gffs){return;}
            BASIC(CMD_FADEDEFAULT);
            ec();
          }
          aa("cmd_c3")
          {
            vlog("CMD_C3\r\n");
            arg1=GetNum("CMD_C3");
            if(!gffs){return;}
            BASIC(CMD_C3);
            rom(arg1,1);
            ec();
          }
          aa("warp")
          {
            vlog("WARP\r\n");
            arg1=GetNum("WARP");
            if(!gffs){return;}
            arg2=GetNum("WARP");
            if(!gffs){return;}
            arg3=GetNum("WARP");
            if(!gffs){return;}
            if(mode==FIRE_RED)
            {
              arg4=GetNum("WARP");
              if(!gffs){return;}
              arg5=GetNum("WARP");
              if(!gffs){return;}
            }
            BASIC(CMD_WARP);
            rom(arg1,1);
            rom(arg2,1);
            rom(arg3,1);
            if(mode==FIRE_RED)
            {
              rom(arg4,2);
              rom(arg5,2);
            }
            ec();
          }
          aa("removeitem")
          {
            vlog("REMOVEITEM\r\n");
            arg1=GetNum("REMOVEITEM");
            if(!gffs){return;}
            arg2=GetNum("REMOVEITEM");
            if(!gffs){return;}
            BASIC(CMD_REMOVEITEM);
            rom(arg1,2);
            rom(arg2,2);
            ec();
          }
          aa("checkitem")
          {
            vlog("CHECKITEM\r\n");
            arg1=GetNum("CHECKITEM");
            if(!gffs){return;}
            arg2=GetNum("CHECKITEM");
            if(!gffs){return;}
            BASIC(CMD_CHECKITEM);
            rom(arg1,2);
            rom(arg2,2);
            ec();
          }
          aa("checkitemamount")
          {
            vlog("CHECKITEMAMOUNT\r\n");
            arg1=GetNum("CHECKITEMAMOUNT");
            if(!gffs){return;}
            arg2=GetNum("CHECKITEMAMOUNT");
            if(!gffs){return;}
            BASIC(CMD_CHECKITEMAMOUNT);
            rom(arg1,2);
            rom(arg2,2);
            ec();
          }
          aa("cmd_2c")
          {
            vlog("CMD_2C\r\n");
            arg1=GetNum("CMD_2C");
            if(!gffs){return;}
            arg2=GetNum("CMD_2C");
            if(!gffs){return;}
            BASIC(CMD_2C);
            rom(arg1,2);
            rom(arg2,2);
            ec();
          }
          aa("checkattack")
          {
            vlog("CHECKATTACK\r\n");
            arg1=GetNum("CHECKATTACK");
            if(!gffs){return;}
            BASIC(CMD_CHECKATTACK);
            rom(arg1,2);
            ec();
          }
          aa("applymovement")
          {
            vlog("APPLYMOVEMENT\r\n");
            arg1=GetNum("APPLYMOVEMENT");
            if(!gffs){return;}
            arg2=GetNum("APPLYMOVEMENT");
            if(!gffs){return;}
            BASIC(CMD_APPLYMOVEMENT);
            if((arg2&0xff000000)==0)
            {
              arg2|=0x08000000;
              sprintf(buf3,"   -> Converted to 0x%x\r\n",arg2);
              vlog(buf3);
            }
            rom(arg1,2);
            rom(arg2,4);
            ec();
          }
          aa("applymovementfinishat")
          {
            vlog("APPLYMOVEMENTFINISHAT\r\n");
            arg1=GetNum("APPLYMOVEMENTFINISHAT");
            if(!gffs){return;}
            arg2=GetNum("APPLYMOVEMENTFINISHAT");
            if(!gffs){return;}
            arg3=GetNum("APPLYMOVEMENTFINISHAT");
            if(!gffs){return;}
            arg4=GetNum("APPLYMOVEMENTFINISHAT");
            if(!gffs){return;}
            BASIC(CMD_APPLYMOVEMENTFINISHAT);
            if((arg2&0xff000000)==0)
            {
              arg2|=0x08000000;
              sprintf(buf3,"   -> Converted to 0x%x\r\n",arg2);
              vlog(buf3);
            }
            rom(arg1,2);
            rom(arg2,4);
            rom(arg3,1);
            rom(arg4,1);
            ec();
          }
          aa("pauseevent")
          {
            vlog("PAUSEEVENT\r\n");
            arg1=GetNum("PAUSEEVENT");
            if(!gffs){return;}
            BASIC(CMD_PAUSEEVENT);
            rom(arg1,2);
            ec();
          }
          aa("checkfurniture")
          {
            vlog("CHECKFURNITURE\r\n");
            arg1=GetNum("CHECKFURNITURE");
            if(!gffs){return;}
            BASIC(CMD_CHECKFURNITURE);
            rom(arg1,2);
            ec();
          }
          aa("checkifroomforfurniture")
          {
            vlog("CHECKIFROOMFORFURNITURE\r\n");
            arg1=GetNum("CHECKIFROOMFORFURNITURE");
            if(!gffs){return;}
            BASIC(CMD_CHECKIFROOMFORFURNITURE);
            rom(arg1,2);
            ec();
          }
          aa("takefurniture")
          {
            vlog("TAKEFURNITURE\r\n");
            arg1=GetNum("TAKEFURNITURE");
            if(!gffs){return;}
            BASIC(CMD_TAKEFURNITURE);
            rom(arg1,2);
            ec();
          }
          aa("addfurniture")
          {
            vlog("ADDFURNITURE\r\n");
            arg1=GetNum("ADDFURNITURE");
            if(!gffs){return;}
            BASIC(CMD_ADDFURNITURE);
            rom(arg1,2);
            ec();
          }
          aa("checkitemtype")
          {
            vlog("CHECKITEMTYPE\r\n");
            arg1=GetNum("CHECKITEMTYPE");
            if(!gffs){return;}
            BASIC(CMD_CHECKITEMTYPE);
            rom(arg1,2);
            ec();
          }
          aa("checkiteminpc")
          {
            vlog("CHECKITEMINPC\r\n");
            arg1=GetNum("CHECKITEMINPC");
            if(!gffs){return;}
            arg2=GetNum("CHECKITEMINPC");
            if(!gffs){return;}
            BASIC(CMD_CHECKITEMINPC);
            rom(arg1,2);
            rom(arg2,2);
            ec();
          }
          aa("giveitemtopc")
          {
            vlog("GIVEITEMTOPC\r\n");
            arg1=GetNum("GIVEITEMTOPC");
            if(!gffs){return;}
            arg2=GetNum("GIVEITEMTOPC");
            if(!gffs){return;}
            BASIC(CMD_GIVEITEMTOPC);
            rom(arg1,2);
            rom(arg2,2);
            ec();
          }
          aa("createtempsprite")
          {
            vlog("CREATETEMPSPRITE\r\n");
            arg1=GetNum("CREATETEMPSPRITE");
            if(!gffs){return;}
            arg2=GetNum("CREATETEMPSPRITE");
            if(!gffs){return;}
            arg3=GetNum("CREATETEMPSPRITE");
            if(!gffs){return;}
            arg4=GetNum("CREATETEMPSPRITE");
            if(!gffs){return;}
            arg5=GetNum("CREATETEMPSPRITE");
            if(!gffs){return;}
            arg6=GetNum("CREATETEMPSPRITE");
            if(!gffs){return;}
            BASIC(CMD_CREATETEMPSPRITE);
            rom(arg1,1);
            rom(arg2,1);
            rom(arg3,2);
            rom(arg4,2);
            rom(arg5,1);
            rom(arg6,1);
            ec();
          }
          aa("tempspriteface")
          {
            vlog("TEMPSPRITEFACE\r\n");
            arg1=GetNum("TEMPSPRITEFACE");
            if(!gffs){return;}
            arg2=GetNum("TEMPSPRITEFACE");
            if(!gffs){return;}
            BASIC(CMD_TEMPSPRITEFACE);
            rom(arg1,1);
            rom(arg2,1);
            ec();
          }
          aa("cmd_a6")
          {
            vlog("CMD_A6\r\n");
            arg1=GetNum("CMD_A6");
            if(!gffs){return;}
            BASIC(CMD_A6);
            rom(arg1,1);
            ec();
          }
          aa("trainerbattle")
          {
            vlog("TRAINERBATTLE\r\n");
            arg1=GetNum("TRAINERBATTLE");
            if(!gffs){return;}
            arg2=GetNum("TRAINERBATTLE");
            if(!gffs){return;}
            arg3=GetNum("TRAINERBATTLE");
            if(!gffs){return;}
            arg4=GetNum("TRAINERBATTLE");
            if(!gffs){return;}
            if((arg4&0xff000000)==0)
            {
              arg4|=0x08000000;
              sprintf(buf3,"   -> Converted to 0x%x\r\n",arg4);
              vlog(buf3);
            }
            arg5=GetNum("TRAINERBATTLE");
            if(!gffs){return;}
            if((arg4&0xff000000)==0)
            {
              arg4|=0x08000000;
              sprintf(buf3,"   -> Converted to 0x%x\r\n",arg4);
              vlog(buf3);
            }
            BASIC(CMD_TRAINERBATTLE);
            rom(arg1,1);
            rom(arg2,2);
            rom(arg3,2);
            rom(arg4,4);
            rom(arg5,4);
            if(arg1==1)
            {
              arg6=GetNum("TRAINERBATTLE");
              if(!gffs){return;}
              rom(arg6,4);
            }
            ec();
          }
          aa("cmd_b1")
          {
            vlog("CMD_B1\r\n");
            arg1=GetNum("CMD_B1");
            if(!gffs){return;}
            arg2=GetNum("CMD_B1");
            if(!gffs){return;}
            arg3=GetNum("CMD_B1");
            if(!gffs){return;}
            arg4=GetNum("CMD_B1");
            if(!gffs){return;}
            BASIC(CMD_B1);
            rom(arg1,1);
            rom(arg2,1);
            rom(arg3,2);
            rom(arg4,2);
            ec();
          }
          aa("multichoice")
          {
            vlog("MULTICHOICE\r\n");
            arg1=GetNum("MULTICHOICE");
            if(!gffs){return;}
            arg2=GetNum("MULTICHOICE");
            if(!gffs){return;}
            arg3=GetNum("MULTICHOICE");
            if(!gffs){return;}
            arg4=GetNum("MULTICHOICE");
            if(!gffs){return;}
            BASIC(CMD_MULTICHOICE);
            rom(arg1,1);
            rom(arg2,1);
            rom(arg3,1);
            rom(arg4,1);
            ec();
          }
          aa("picture")
          {
            vlog("PICTURE\r\n");
            arg1=GetNum("PICTURE");
            if(!gffs){return;} //GFFS stands for Get-For-Function success. GetNum sets this to 0 on failure.
            BASIC(CMD_PICTURE);
            rom(arg1,1);
            ec();
          }
          aa("braille")
          {
            vlog("BRAILLE\r\n");
            arg1=GetNum("BRAILLE");
            if(!gffs){return;}
            BASIC(CMD_BRAILLE);
            if((arg1&0xff000000)==0)
            {
              arg1|=0x08000000;
              sprintf(buf3,"   -> Converted to 0x%x\r\n",arg1);
              vlog(buf3);
            }
            rom(arg1,4);
            ec();
          }
          aa("cmd_d3")
          {
            vlog("CMD_D3\r\n");
            arg1=GetNum("CMD_D3");
            if(!gffs){return;}
            BASIC(CMD_D3);
            if((arg1&0xff000000)==0)
            {
              arg1|=0x08000000;
              sprintf(buf3,"   -> Converted to 0x%x\r\n",arg1);
              vlog(buf3);
            }
            rom(arg1,4);
            ec();
          }
          aa("cmd_fb")
          {
            vlog("CMD_FB\r\n");
            arg1=GetNum("CMD_FB");
            if(!gffs){return;}
            BASIC(CMD_FB);
            if((arg1&0xff000000)==0)
            {
              arg1|=0x08000000;
              sprintf(buf3,"   -> Converted to 0x%x\r\n",arg1);
              vlog(buf3);
            }
            rom(arg1,4);
            ec();
          }
          aa("addpokemon")
          {
            vlog("ADDPOKEMON\r\n");
            arg1=GetNum("ADDPOKEMON");
            if(!gffs){return;}
            arg2=GetNum("ADDPOKEMON");
            if(!gffs){return;}
            arg3=GetNum("ADDPOKEMON");
            if(!gffs){return;}
            arg4=GetNum("ADDPOKEMON");
            if(!gffs){return;}
            arg5=GetNum("ADDPOKEMON");
            if(!gffs){return;}
            arg6=GetNum("ADDPOKEMON");
            if(!gffs){return;}
            BASIC(CMD_ADDPOKEMON);
            rom(arg1,2);
            rom(arg2,1);
            rom(arg3,2);
            rom(arg4,1);
            rom(arg5,4);
            rom(arg6,4);
            ec();
          }
          aa("storepokemon")
          {
            vlog("STOREPOKEMON\r\n");
            arg1=GetNum("STOREPOKEMON");
            if(!gffs){return;}
            arg2=GetNum("STOREPOKEMON");
            if(!gffs){return;}
            BASIC(CMD_STOREPOKEMON);
            rom(arg1,1);
            rom(arg2,2);
            ec();
          }
          aa("storeboxname")
          {
            vlog("STOREBOXNAME\r\n");
            arg1=GetNum("STOREBOXNAME");
            if(!gffs){return;}
            arg2=GetNum("STOREBOXNAME");
            if(!gffs){return;}
            BASIC(CMD_STOREBOXNAME);
            rom(arg1,1);
            rom(arg2,2);
            ec();
          }
          aa("storevar")
          {
            vlog("STOREVAR\r\n");
            arg1=GetNum("STOREVAR");
            if(!gffs){return;}
            arg2=GetNum("STOREVAR");
            if(!gffs){return;}
            BASIC(CMD_STOREVAR);
            rom(arg1,1);
            rom(arg2,2);
            ec();
          }
          aa("storetext")
          {
            vlog("STORETEXT\r\n");
            arg1=GetNum("STORETEXT");
            if(!gffs){return;}
            arg2=GetNum("STORETEXT");
            if(!gffs){return;}
            BASIC(CMD_STORETEXT);
            rom(arg1,1);
            if((arg2&0xff000000)==0)
            {
              arg2|=0x08000000;
              sprintf(buf3,"   -> Converted to 0x%x\r\n",arg2);
              vlog(buf3);
            }
            rom(arg2,4);
            ec();
          }
          aa("pokemart")
          {
            vlog("POKEMART\r\n");
            arg1=GetNum("POKEMART");
            if(!gffs){return;}
            if((arg1&0xff000000)==0)
            {
              arg1|=0x08000000;
              sprintf(buf3,"   -> Converted to 0x%x\r\n",arg1);
              vlog(buf3);
            }
            BASIC(CMD_POKEMART);
            rom(arg1,4);
            ec();
          }
          aa("pokemart2")
          {
            vlog("POKEMART2\r\n");
            arg1=GetNum("POKEMART2");
            if(!gffs){return;}
            if((arg1&0xff000000)==0)
            {
              arg1|=0x08000000;
              sprintf(buf3,"   -> Converted to 0x%x\r\n",arg1);
              vlog(buf3);
            }
            BASIC(CMD_POKEMART2);
            rom(arg1,4);
            ec();
          }
          aa("pokemart3")
          {
            vlog("POKEMART3\r\n");
            arg1=GetNum("POKEMART3");
            if(!gffs){return;}
            if((arg1&0xff000000)==0)
            {
              arg1|=0x08000000;
              sprintf(buf3,"   -> Converted to 0x%x\r\n",arg1);
              vlog(buf3);
            }
            BASIC(CMD_POKEMART3);
            rom(arg1,4);
            ec();
          }
          aa("setmaptile")
          {
            vlog("SETMAPTILE\r\n");
            arg1=GetNum("SETMAPTILE");
            if(!gffs){return;}
            arg2=GetNum("SETMAPTILE");
            if(!gffs){return;}
            arg3=GetNum("SETMAPTILE");
            if(!gffs){return;}
            arg4=GetNum("SETMAPTILE");
            if(!gffs){return;}
            BASIC(CMD_SETMAPTILE);
            rom(arg1,2);
            rom(arg2,2);
            rom(arg3,2);
            rom(arg4,2);
            ec();
          }
          aa("setmapfooter")
          {
            vlog("SETMAPFOOTER\r\n");
            arg1=GetNum("SETMAPFOOTER");
            if(!gffs){return;}
            BASIC(CMD_SETMAPFOOTER);
            rom(arg1,2);
            ec();
          }
          aa("setweather")
          {
            vlog("SETWEATHER\r\n");
            arg1=GetNum("SETWEATHER");
            if(!gffs){return;}
            BASIC(CMD_SETWEATHER);
            arg2=1;
            if(mode==FIRE_RED)arg2=2;
            rom(arg1,arg2);
            ec();
          }
          aa("battle")
          {
            vlog("BATTLE\r\n");
            arg1=GetNum("BATTLE");
            if(!gffs){return;}
            arg2=GetNum("BATTLE");
            if(!gffs){return;}
            arg3=GetNum("BATTLE");
            if(!gffs){return;}
            BASIC(CMD_BATTLE);
            rom(arg1,2);
            rom(arg2,1);
            rom(arg3,2);
            ec();
          }
          aa("resetspritelevel")
          {
            vlog("RESETSPRITELEVEL\r\n");
            arg1=GetNum("RESETSPRITELEVEL");
            if(!gffs){return;}
            arg2=GetNum("RESETSPRITELEVEL");
            if(!gffs){return;}
            arg3=GetNum("RESETSPRITELEVEL");
            if(!gffs){return;}
            BASIC(CMD_RESETSPRITELEVEL);
            rom(arg1,2);
            rom(arg2,2);
            rom(arg3,2);
            ec();
          }
          aa("hidebox")
          {
            vlog("HIDEBOX\r\n");
            arg1=GetNum("HIDEBOX");
            if(!gffs){return;}
            arg2=GetNum("HIDEBOX");
            if(!gffs){return;}
            arg3=GetNum("HIDEBOX");
            if(!gffs){return;}
            arg4=GetNum("HIDEBOX");
            if(!gffs){return;}
            BASIC(CMD_HIDEBOX);
            rom(arg1,1);
            rom(arg2,1);
            rom(arg3,1);
            rom(arg4,1);
            ec();
          }
          aa("storeitem")
          {
            vlog("STOREITEM\r\n");
            arg1=GetNum("STOREITEM");
            if(!gffs){return;}
            arg2=GetNum("STOREITEM");
            if(!gffs){return;}
            BASIC(CMD_STOREITEM);
            rom(arg1,1);
            rom(arg2,2);
            ec();
          }
          aa("storeatk")
          {
            vlog("STOREATK\r\n");
            arg1=GetNum("STOREATK");
            if(!gffs){return;}
            arg2=GetNum("STOREATK");
            if(!gffs){return;}
            BASIC(CMD_STOREATK);
            rom(arg1,1);
            rom(arg2,2);
            ec();
          }
          aa("storefurniture")
          {
            vlog("STOREFURNITURE\r\n");
            arg1=GetNum("STOREFURNITURE");
            if(!gffs){return;}
            arg2=GetNum("STOREFURNITURE");
            if(!gffs){return;}
            BASIC(CMD_STOREFURNITURE);
            rom(arg1,1);
            rom(arg2,2);
            ec();
          }
          aa("storecomp")
          {
            vlog("STORECOMP\r\n");
            arg1=GetNum("STORECOMP");
            if(!gffs){return;}
            arg2=GetNum("STORECOMP");
            if(!gffs){return;}
            BASIC(CMD_STORECOMP);
            rom(arg1,1);
            rom(arg2,2);
            ec();
          }
          aa("checkattack")
          {
            vlog("CHECKATTACK\r\n");
            arg1=GetNum("CHECKATTACK");
            if(!gffs){return;}
            arg2=GetNum("CHECKATTACK");
            if(!gffs){return;}
            BASIC(CMD_CHECKATTACK);
            rom(arg1,1);
            rom(arg2,2);
            ec();
          }
          aa("namepokemon")
          {
            BASIC(CMD_FADESCREEN);
            BASIC(1);
            BASIC(CMD_SPECIAL);
            rom(0x9E,2);
            BASIC(CMD_WAITSPECIAL);
            ec();
          }
          aa("slotmachine")
          {
            vlog("SLOTMACHINE\r\n");
            arg1=GetNum("SLOTMACHINE");
            if(!gffs){return;}
            BASIC(CMD_SLOTMACHINE);
            rom(arg1,2);
            ec();
          }
          aa("giveegg")
          {
            vlog("GIVEEGG\r\n");
            arg1=GetNum("GIVEEGG");
            if(!gffs){return;}
            BASIC(CMD_GIVEEGG);
            rom(arg1,2);
            ec();
          }
          aa("disappear")
          {
            vlog("DISAPPEAR\r\n");
            arg1=GetNum("DISAPPEAR");
            if(!gffs){return;}
            BASIC(CMD_DISAPPEAR);
            rom(arg1,2);
            ec();
          }
          aa("reappear")
          {
            vlog("REAPPEAR\r\n");
            arg1=GetNum("REAPPEAR");
            if(!gffs){return;}
            BASIC(CMD_REAPPEAR);
            rom(arg1,2);
            ec();
          }
          aa("showmoney")
          {
            vlog("SHOWMONEY\r\n");
            arg1=GetNum("SHOWMONEY");
            if(!gffs){return;}
            arg2=GetNum("SHOWMONEY");
            if(!gffs){return;}
            BASIC(CMD_SHOWMONEY);
            rom(arg1,2);
            rom(arg2,1);
            ec();
          }
          aa("multichoice2")
          {
            vlog("MULTICHOICE2\r\n");
            arg1=GetNum("MULTICHOICE2");
            if(!gffs){return;}
            arg2=GetNum("MULTICHOICE2");
            if(!gffs){return;}
            arg3=GetNum("MULTICHOICE2");
            if(!gffs){return;}
            arg4=GetNum("MULTICHOICE2");
            if(!gffs){return;}
            BASIC(CMD_MULTICHOICE2);
            rom(arg1,1);
            rom(arg2,1);
            rom(arg3,1);
            rom(arg4,2);
            ec();
          }
          aa("multichoice3")
          {
            vlog("MULTICHOICE3\r\n");
            arg1=GetNum("MULTICHOICE3");
            if(!gffs){return;}
            arg2=GetNum("MULTICHOICE3");
            if(!gffs){return;}
            arg3=GetNum("MULTICHOICE3");
            if(!gffs){return;}
            arg4=GetNum("MULTICHOICE3");
            if(!gffs){return;}
            arg5=GetNum("MULTICHOICE3");
            if(!gffs){return;}
            BASIC(CMD_MULTICHOICE3);
            rom(arg1,1);
            rom(arg2,1);
            rom(arg3,1);
            rom(arg4,1);
            rom(arg5,1);
            ec();
          }
          aa("showyesno")
          {
            vlog("SHOWYESNO\r\n");
            arg1=GetNum("SHOWYESNO");
            if(!gffs){return;}
            arg2=GetNum("SHOWYESNO");
            if(!gffs){return;}
            BASIC(CMD_SHOWYESNO);
            rom(arg1,1);
            rom(arg2,1);
            ec();
          }
          aa("settrainerflag")
          {
            vlog("SETTRAINERFLAG\r\n");
            arg1=GetNum("SETTRAINERFLAG");
            if(!gffs){return;}
            BASIC(CMD_SETTRAINERFLAG);
            rom(arg1,2);
            ec();
          }
          aa("hidecoins")
          {
            vlog("HIDECOINS\r\n");
            arg1=GetNum("HIDECOINS");
            if(!gffs){return;}
            arg2=GetNum("HIDECOINS");
            if(!gffs){return;}
            BASIC(CMD_HIDECOINS);
            rom(arg1,1);
            rom(arg2,1);
            ec();
          }
          aa("showcoins")
          {
            vlog("SHOWCOINS\r\n");
            arg1=GetNum("SHOWCOINS");
            if(!gffs){return;}
            arg2=GetNum("SHOWCOINS");
            if(!gffs){return;}
            BASIC(CMD_SHOWCOINS);
            rom(arg1,1);
            rom(arg2,1);
            ec();
          }
          aa("hidemoney")
          {
            vlog("HIDEMONEY\r\n");
            arg1=GetNum("HIDEMONEY");
            if(!gffs){return;}
            BASIC(CMD_HIDEMONEY);
            rom(arg1,2);
            ec();
          }
          aa("coincasetovar")
          {
            vlog("CoinCaseToVar\r\n");
            arg1=GetNum("COINCASETOVAR");
            if(!gffs){return;}
            BASIC(CMD_COINCASETOVAR);
            rom(arg1,2);
            ec();
          }
          aa("givetocoincase")
          {
            vlog("GIVETOCOINCASE\r\n");
            arg1=GetNum("GIVETOCOINCASE");
            if(!gffs){return;}
            BASIC(CMD_GIVETOCOINCASE);
            rom(arg1,2);
            ec();
          }
          aa("takefromcoincase")
          {
            vlog("TAKEFROMCOINCASE\r\n");
            arg1=GetNum("TAKEFROMCOINCASE");
            if(!gffs){return;}
            BASIC(CMD_TAKEFROMCOINCASE);
            rom(arg1,2);
            ec();
          }
          aa("updatemoney")
          {
            vlog("UPDATEMONEY\r\n");
            arg1=GetNum("UPDATEMONEY");
            if(!gffs){return;}
            arg2=GetNum("UPDATEMONEY");
            if(!gffs){return;}
            arg3=GetNum("UPDATEMONEY");
            if(!gffs){return;}
            BASIC(CMD_UPDATEMONEY);
            rom(arg1,1);
            rom(arg2,1);
            rom(arg3,1);
            ec();
          }
          aa("callstdif")
          {
            vlog("callstdif\r\n");
            arg1=GetNum("callstdif");
            if(!gffs){return;}
            arg2=GetNum("callstdif");
            if(!gffs){return;}
            BASIC(CMD_CALLSTDIF);
            rom(arg1,1);
            rom(arg2,1);
            ec();
          }
          aa("jumpstdif")
          {
            vlog("jumpstdif\r\n");
            arg1=GetNum("jumpstdif");
            if(!gffs){return;}
            arg2=GetNum("jumpstdif");
            if(!gffs){return;}
            BASIC(CMD_JUMPSTDIF);
            rom(arg1,1);
            rom(arg2,1);
            ec();
          }
          aa("checkmoney")
          {
            vlog("CHECKMONEY\r\n");
            arg1=GetNum("CHECKMONEY");
            if(!gffs){return;}
            arg2=GetNum("CHECKMONEY");
            if(!gffs){return;}
            BASIC(CMD_CHECKMONEY);
            rom(arg1,2);
            rom(arg2,1);
            ec();
          }
          aa("paymoney")
          {
            vlog("PAYMONEY\r\n");
            arg1=GetNum("PAYMONEY");
            if(!gffs){return;}
            arg2=GetNum("PAYMONEY");
            if(!gffs){return;}
            BASIC(CMD_PAYMONEY);
            rom(arg1,2);
            rom(arg2,1);
            ec();
          }
          aa("givemoney")
          {
            vlog("GIVEMONEY\r\n");
            arg1=GetNum("GIVEMONEY");
            if(!gffs){return;}
            arg2=GetNum("GIVEMONEY");
            if(!gffs){return;}
            BASIC(CMD_GIVEMONEY);
            rom(arg1,4);
            rom(arg2,1);
            ec();
          }
          aa("cmd_96")
          {
            vlog("CMD_96\r\n");
            arg1=GetNum("CMD_96");
            if(!gffs){return;}
            BASIC(CMD_96);
            rom(arg1,2);
            ec();
          }
          aa("addvar")
          {
            vlog("ADDVAR\r\n");
            arg1=GetNum("ADDVAR");
            if(!gffs){return;}
            arg2=GetNum("ADDVAR");
            if(!gffs){return;}
            BASIC(CMD_ADDVAR);
            rom(arg1,2);
            rom(arg2,2);
            ec();
          }
          aa("subtractvar")
          {
            vlog("SUBTRACTVAR\r\n");
            arg1=GetNum("SUBTRACTVAR");
            if(!gffs){return;}
            arg2=GetNum("SUBTRACTVAR");
            if(!gffs){return;}
            BASIC(CMD_SUBTRACTVAR);
            rom(arg1,2);
            rom(arg2,2);
            ec();
          }
          aa("setfarbyte")
          {
            vlog("SETFARBYTE\r\n");
            arg1=GetNum("SETFARBYTE");
            if(!gffs){return;}
            arg2=GetNum("SETFARBYTE");
            if(!gffs){return;}
            BASIC(CMD_SETFARBYTE);
            rom(arg1,1);
            rom(arg2,4);
            ec();
          }
          aa("setbyte2")
          {
            vlog("SETBYTE2\r\n");
            arg1=GetNum("SETBYTE2");
            if(!gffs){return;}
            arg2=GetNum("SETBYTE2");
            if(!gffs){return;}
            BASIC(CMD_SETBYTE2);
            rom(arg1,1);
            rom(arg2,1);
            ec();
          }
          aa("cmd_fe")
          {
            vlog("CMD_FE\r\n");
            arg1=GetNum("CMD_FE");
            if(!gffs){return;}
            BASIC(CMD_FE);
            rom(arg1,1);
            ec();
          }
          aa("cleartrainerflag")
          {
            vlog("CLEARTRAINERFLAG\r\n");
            arg1=GetNum("CLEARTRAINERFLAG");
            if(!gffs){return;}
            BASIC(CMD_CLEARTRAINERFLAG);
            rom(arg1,2);
            ec();
          }
          aa("movesprite2")
          {
            vlog("movesprite2\r\n");
            arg1=GetNum("movesprite2");
            if(!gffs){return;}
            arg2=GetNum("movesprite2");
            if(!gffs){return;}
            arg3=GetNum("movesprite2");
            if(!gffs){return;}
            BASIC(CMD_MOVESPRITE2);
            rom(arg1,2);
            rom(arg2,2);
            rom(arg3,2);
            ec();
          }
          aa("spritebehave")
          {
            vlog("spritebehave\r\n");
            arg1=GetNum("spritebehave");
            if(!gffs){return;}
            arg2=GetNum("spritebehave");
            if(!gffs){return;}
            BASIC(CMD_SPRITEBEHAVE);
            rom(arg1,2);
            rom(arg2,2);
            ec();
          }
          aa("comparevars")
          {
            vlog("COMPAREVARS\r\n");
            arg1=GetNum("COMPAREVARS");
            if(!gffs){return;}
            arg2=GetNum("COMPAREVARS");
            if(!gffs){return;}
            BASIC(CMD_COMPAREVARS);
            rom(arg1,2);
            rom(arg2,2);
            ec();
          }
          aa("comparevars2")
          {
            vlog("COMPAREVARS2\r\n");
            arg1=GetNum("COMPAREVARS2");
            if(!gffs){return;}
            arg2=GetNum("COMPAREVARS2");
            if(!gffs){return;}
            BASIC(CMD_COMPAREVARS2);
            rom(arg1,2);
            rom(arg2,2);
            ec();
          }
          aa("textcolor")
          {
            vlog("TEXTCOLOR\r\n");
            arg1=GetNum("TEXTCOLOR");
            if(!gffs){return;}
            BASIC(CMD_TEXTCOLOR);
            rom(arg1,1);
            ec();
          }
          aa("fakejumpstd")
          {
            vlog("FAKEJUMPSTD\r\n");
            arg1=GetNum("FAKEJUMPSTD");
            if(!gffs){return;}
            BASIC(CMD_FAKEJUMPSTD);
            rom(arg1,1);
            ec();
          }
          aa("fakecallstd")
          {
            vlog("FAKECALLSTD\r\n");
            arg1=GetNum("FAKECALLSTD");
            if(!gffs){return;}
            BASIC(CMD_FAKECALLSTD);
            rom(arg1,1);
            ec();
          }
          aa("textcolour")
          {
            vlog("TEXTCOLOR\r\n");
            arg1=GetNum("TEXTCOLOR");
            if(!gffs){return;}
            BASIC(CMD_TEXTCOLOR);
            rom(arg1,1);
            ec();
          }
          aa("additem")
          {
            vlog("ADDITEM\r\n");
            arg1=GetNum("ADDITEM");
            if(!gffs){return;}
            arg2=GetNum("ADDITEM");
            if(!gffs){return;}
            BASIC(CMD_ADDITEM);
            rom(arg1,2);
            rom(arg2,2);
            ec();
          }
          aa("darkenroom")
          {
            vlog("DARKENROOM\r\n");
            arg1=GetNum("DARKENROOM");
            if(!gffs){return;}
            BASIC(CMD_DARKENROOM);
            rom(arg1,2);
            ec();
          }
          aa("lightroom")
          {
            vlog("LIGHTROOM\r\n");
            arg1=GetNum("LIGHTROOM");
            if(!gffs){return;}
            BASIC(CMD_LIGHTROOM);
            rom(arg1,1);
            ec();
          }
          aa("checktrainerflag")
          {
            vlog("CHECKTRAINERFLAG\r\n");
            arg1=GetNum("CHECKTRAINERFLAG");
            if(!gffs){return;}
            BASIC(CMD_CHECKTRAINERFLAG);
            rom(arg1,2);
            ec();
          }
          aa("reappearat")
          {
            vlog("REAPPEARAT\r\n");
            arg1=GetNum("REAPPEARAT");
            if(!gffs){return;}
            arg2=GetNum("REAPPEARAT");
            if(!gffs){return;}
            arg3=GetNum("REAPPEARAT");
            if(!gffs){return;}
            BASIC(CMD_REAPPEARAT);
            rom(arg1,2);
            rom(arg2,1);
            rom(arg3,1);
            ec();
          }
          aa("disappearat")
          {
            vlog("DISAPPEARAT\r\n");
            arg1=GetNum("DISAPPEARAT");
            if(!gffs){return;}
            arg2=GetNum("DISAPPEARAT");
            if(!gffs){return;}
            arg3=GetNum("DISAPPEARAT");
            if(!gffs){return;}
            BASIC(CMD_DISAPPEARAT);
            rom(arg1,2);
            rom(arg2,1);
            rom(arg3,1);
            ec();
          }
          aa("movesprite")
          {
            vlog("MOVESPRITE\r\n");
            arg1=GetNum("MOVESPRITE");
            if(!gffs){return;}
            arg2=GetNum("MOVESPRITE");
            if(!gffs){return;}
            arg3=GetNum("MOVESPRITE");
            if(!gffs){return;}
            BASIC(CMD_MOVESPRITE);
            rom(arg1,2);
            rom(arg2,2);
            rom(arg3,2);
            ec();
          }
          aa("farreappear")
          {
            vlog("FARREAPPEAR\r\n");
            arg1=GetNum("FARREAPPEAR");
            if(!gffs){return;}
            arg2=GetNum("FARREAPPEAR");
            if(!gffs){return;}
            arg3=GetNum("FARREAPPEAR");
            if(!gffs){return;}
            BASIC(CMD_FARREAPPEAR);
            rom(arg1,2);
            rom(arg2,1);
            rom(arg3,1);
            ec();
          }
          aa("fardisappear")
          {
            vlog("FARDISAPPEAR\r\n");
            arg1=GetNum("FARDISAPPEAR");
            if(!gffs){return;}
            arg2=GetNum("FARDISAPPEAR");
            if(!gffs){return;}
            arg3=GetNum("FARDISAPPEAR");
            if(!gffs){return;}
            BASIC(CMD_FARDISAPPEAR);
            rom(arg1,2);
            rom(arg2,1);
            rom(arg3,1);
            ec();
          }
          aa("moveoffscreen")
          {
            vlog("MOVEOFFSCREEN\r\n");
            arg1=GetNum("MOVEOFFSCREEN");
            if(!gffs){return;}
            BASIC(CMD_MOVEOFFSCREEN);
            rom(arg1,2);
            ec();
          }
          aa("m")
          {
            vlog("Movement data...\r\n");
            WriteFile(RomFile,trans,transbackmove(Script,&i),&read,NULL);
            ec();
          }
          aa("=")
          {
            vlog("[STRING]\r\n");
            if(chr==' '){i++;}
            else{log("Should have a space after the =\r\n",33);}
            temp_ptr=transbackstr(script,i-SetFilePointer(IncFile,0,NULL,FILE_END)-1,RomFile);
            while(chr!='\n'&&chr!=0){i++;}
            sprintf(buf2,"   -> %s\r\n",temp_ptr);
            GlobalFree(temp_ptr);
            vlog(buf2);
          }
          aa(".")
          {
            vlog("[BINARY]\r\n   ->");
            while(chr==' '){i++;}
            k=0;
            while(chr!='\n'&&chr!=0)
            {
              k=1-k;
              while(chr==' ')
              {i++;}
              j=0;
              while(((char*)("0123456789abcdef"))[j]!=0)
              {
                if(((char*)("0123456789abcdef"))[j]==chr)
                {
                  break;
                }
                j+=1;
              }
              if(((char*)("0123456789abcdef"))[j]==0)
              {
                sprintf(buf2,"Failed to understand hex character '%c'\r\n",chr);
                log(buf2,strlen(buf2));
                return;
              }
              if(k==0)
              {
                l|=j;
                rom(j,1);
                if(IsVerbose)
                {
                  sprintf(buf2," %02X",l);
                  log(buf2,strlen(buf2));
                }
              }
              else
              {
                l=j<<4;
              }
              i++;
            }
            vlog("\r\n");
          }
          else
          {
            sprintf(buf2,"Warning: Unknown command \"%s\"\r\n",buf);
            log(buf2,strlen(buf2));
            while(chr!='\n'&&chr!=0)
            {
              i++;
            }
          }
          break;
      }
      i++;
    }
    ///WriteFile(LogFile,stuff,fs,&read,NULL);
    GlobalFree(Script);
    CloseHandle(LogFile);
    CloseHandle(IncFile);
    if(strcmp(script,""))CloseHandle(CurrFile);
  }
  else
  {
    printf("Error opening script.");
    return;
  }
  return;
}
