/*
    Charles Daffern (Score_Under)'s PKSV - Pokemon ROM script viewer/editor
    Copyright (C) 2007  Charles Daffern

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
#define log(asd,fgh) WriteFile(LogFile,asd,fgh,&read,NULL)
#define aa(x) else if (!strcmp(buf,x))
#define ec() while(Script[i+1]==' '){i++;}if(Script[i+1]=='\''){while(Script[i+1]!='\n'&&Script[i+1]!=0){i++;}}if(Script[i+1]!='\n'){log("Extra characters on line. Ignoring.\r\n",37);}while(chr!='\n'){i++;}
#define rom(c,s) j=c;WriteFile(RomFile,&j,s,&read,NULL)
#define BASIC(x) rom(x,1)
#define vlog(x,y) vlogProc(LogFile,x,y)
void vlogProc(HANDLE LogFile,char*x,unsigned int y)
{
  DWORD read;
  if (IsVerbose){log(x,y);}
  return;
}
void RecodeProc(char*script,char*romfn)
{
  HANDLE CurrFile,LogFile,IncFile,RomFile;
  char*Script;             //Whoops, used the same name for the filename.
                           //Use caps-lock carefully.
  char buf[1024],buf2[1024],buf3[1024];
  void*temp_ptr;
  unsigned int fs,la,fst,i,line,j,k,l,arg1,arg2,arg3,arg4,arg5,arg6;
  DWORD read;
  SetLastError(0);
  CurrFile=CreateFile(script,GENERIC_READ,FILE_SHARE_READ,NULL,OPEN_EXISTING,FILE_ATTRIBUTE_NORMAL,NULL);
  RomFile=CreateFile(romfn,GENERIC_WRITE,FILE_SHARE_READ|FILE_SHARE_WRITE,NULL,OPEN_EXISTING,FILE_ATTRIBUTE_NORMAL,NULL);
  la=GetLastError();
  IncFile=CreateFile("pokeinc.txt",GENERIC_READ,FILE_SHARE_READ,NULL,OPEN_EXISTING,FILE_ATTRIBUTE_NORMAL,NULL);
  if(IncFile==INVALID_HANDLE_VALUE)
  {
    MessageBox(NULL,"The default includes (pokeinc.txt) could not be opened","Error",0x10);
    CloseHandle(CurrFile);
    return;
  }
  if(la)
  {
    FormatMessage(FORMAT_MESSAGE_FROM_SYSTEM,NULL,la,0,buf,1023,NULL);
    MessageBox(NULL,buf,"Error",0x40);
    CloseHandle(IncFile);
    return;
  }
  if(CurrFile!=INVALID_HANDLE_VALUE)
  {
    SetLastError(0);
    fs=GetFileSize(CurrFile,NULL);
    fst=GetFileSize(IncFile,NULL);
    la=GetLastError();
    if(la)
    {
      FormatMessage(FORMAT_MESSAGE_FROM_SYSTEM,NULL,la,0,buf,1023,NULL);
      MessageBox(NULL,buf,"Error",0x40);
      if(strcmp(script,""))CloseHandle(CurrFile);
      CloseHandle(IncFile);
      return;
    }
    Script=GlobalAlloc(GPTR,fs+fst+2);
    if(Script==NULL)
    {
      MessageBox(NULL,"GlobalAlloc() Failed to allocate memory for the script.","Error",0x10);
      if(strcmp(script,""))CloseHandle(CurrFile);
      CloseHandle(IncFile);
      return;
    }
    ReadFile(IncFile,Script,fst,&read,NULL);
    strcat(Script,"\n");
    ReadFile(CurrFile,(char*)(Script+fst+1),fs,&read,NULL);
    LogFile=CreateFile("PokeScrE.log",GENERIC_WRITE,FILE_SHARE_READ,NULL,CREATE_ALWAYS,FILE_ATTRIBUTE_NORMAL,NULL);
    if(LogFile==NULL)
    {
      MessageBox(NULL,"Failed to open a log.","Error",0x10);
      GlobalFree(Script);
      if(strcmp(script,""))CloseHandle(CurrFile);
      CloseHandle(IncFile);
      return;
    }
    WriteFile(LogFile,"Opened file.\r\n",14,&read,NULL);
    i=0;
    LowerCase(Script);
    RemAll0D(Script);
    while(i<strlen(Script))
    {
      switch(chr) //Behave differently according to char
      {
        case 0:  //E O Script
          return;
        case '\'':
          while(chr!='\n'&&chr!=0)
          {i++;}i--;break;
        case ' ':  //Ignore spaces
        case '\n':
          break;
        default:
          j=0;
          while(chr!=' '&&chr!='\n'&&chr!=0)
          {
            buf[j]=chr;
            i++;
            j++;
          }
          buf[j]=0;
//aa    is just shorthand for  "else if (!strcmp (buf, x))"
//ec    is End Command
//log   is self-explanatory
//rom   writes to rom
//basic is shorthand for rom(x,1)
          if(!strcmp(buf,"#define"))
          {
            vlog("#DEFINE\r\n",9);
            while(chr==' '){i++;}
            if(chr=='\n'||chr==0)
            {
              log("Premature end to #DEFINE!\r\n",27);
              return;
            }
            j=0;
            while(chr!=' '&&chr!='\n'&&chr!=0)
            {
              buf[j]=chr;
              i++;
              j++;
            }
            buf[j]=0; //Append null
            sprintf(buf2,"   -> %s\r\n",buf);
            vlog(buf2,strlen(buf2));
            while(chr==' '){i++;} //The same old same old.
            if(chr=='\n'||chr==0)
            {
              log("Premature end to #DEFINE!\r\n",27);
              return;
            }
            k=GetNum("#DEFINE");
            if (!gffs){return;}
            Define(buf,k);
            ec();
          }
          aa("#org")
          {
            vlog("#ORG\r\n",6);
            k=GetNum("#ORG");
            if(!gffs){return;}
            SetFilePointer(RomFile,k&0x00ffffff,NULL,FILE_BEGIN);
            ec();
          }
          aa("#raw")
          {
            vlog("#RAW\r\n",6);
            k=GetNum("#RAW");
            if(!gffs){return;}
            BASIC(k);
            if(k>255)
            {
              BASIC(k>>8);
              if(k>65535)
              {
                BASIC(k>>16);
                if(k>16777215)
                {
                  BASIC(k>>24);
                }
              }
            }
            ec();
          }
          aa("end")             {BASIC(CMD_END);          ec();} //BASIC() writes 1 byte to ROM
          aa("return")          {BASIC(CMD_RETURN);       ec();}
          aa("nop")             {BASIC(CMD_NOP0);         ec();}
          aa("nop0")            {BASIC(CMD_NOP0);         ec();}
          aa("nop1")            {BASIC(CMD_NOP1);         ec();}
          aa("checkgender")     {BASIC(CMD_CHECKGENDER);  ec();}
          aa("jingle")          {BASIC(CMD_JINGLE);       ec();}
          aa("closemsg2")       {BASIC(CMD_CLOSEMSG2);    ec();}
          aa("faceplayer")      {BASIC(CMD_FACEPLAYER);   ec();}
          aa("lock")            {BASIC(CMD_LOCK);         ec();}
          aa("release")         {BASIC(CMD_RELEASE);      ec();}
          aa("closemsg")        {BASIC(CMD_CLOSEMSG);     ec();}
          aa("waitbutton")      {BASIC(CMD_WAITBUTTON);   ec();}
          aa("killscript")      {BASIC(CMD_KILLSCRIPT);   ec();}
          aa("waitfanfare")     {BASIC(CMD_WAITFANFARE);  ec();}
          aa("doweather")       {BASIC(CMD_DOWEATHER);    ec();}
          aa("waitspecial")     {BASIC(CMD_WAITSPECIAL);  ec();}
          aa("showmsg")         {BASIC(CMD_SHOWMSG);      ec();}
          aa("fadedefault")     {BASIC(CMD_FADEDEFAULT);  ec();}
          aa("fadeout")         {BASIC(CMD_FADEOUT);      ec();}
          aa("fadein")          {BASIC(CMD_FADEIN);       ec();}
          aa("countpokemon")    {BASIC(CMD_COUNTPOKEMON); ec();}
          aa("msgbox")
          {
            vlog("MSGBOX\r\n",8);
            arg1=GetNum("MSGBOX");
            if(!gffs){return;}
            if((arg1&0xff000000)==0)
            {
              arg1|=0x08000000;
              sprintf(buf3,"   -> Converted to 0x%x\r\n",arg1);
              vlog(buf3,strlen(buf3));
            }
            BASIC(CMD_MSGBOX);
            BASIC(0);
            rom(arg1,4);
            ec();
          }
          aa("loadpointer")
          {
            vlog("LOADPOINTER\r\n",13);
            arg1=GetNum("LOADPOINTER");
            if(!gffs){return;}
            arg2=GetNum("LOADPOINTER");
            if(!gffs){return;}
            if((arg2&0xff000000)==0)
            {
              arg2|=0x08000000;
              sprintf(buf3,"   -> Converted to 0x%x\r\n",arg2);
              vlog(buf3,strlen(buf3));
            }
            BASIC(CMD_MSGBOX);
            BASIC(arg1);
            rom(arg2,4);
            ec();
          }
          aa("call")
          {
            vlog("CALL\r\n",6);
            arg1=GetNum("CALL");
            if(!gffs){return;}
            if((arg1&0xff000000)==0)
            {
              arg1|=0x08000000;
              sprintf(buf3,"   -> Converted to 0x%x\r\n",arg1);
              vlog(buf3,strlen(buf3));
            }
            BASIC(CMD_CALL);
            rom(arg1,4);
            ec();
          }
          aa("jump")
          {
            vlog("JUMP\r\n",6);
            arg1=GetNum("JUMP");
            if(!gffs){return;}
            if((arg1&0xff000000)==0)
            {
              arg1|=0x08000000;
              sprintf(buf3,"   -> Converted to 0x%x\r\n",arg1);
              vlog(buf3,strlen(buf3));
            }
            BASIC(CMD_JUMP);
            rom(arg1,4);
            ec();
          }
          aa("setbyte")
          {
            vlog("SETBYTE\r\n",9);
            arg1=GetNum("SETBYTE");
            if(!gffs){return;}
            BASIC(CMD_SETBYTE);
            BASIC(arg1);
            ec();
          }
          aa("callstd")
          {
            vlog("CALLSTD\r\n",9);
            arg1=GetNum("CALLSTD");
            if(!gffs){return;}
            BASIC(CMD_CALLSTD);
            BASIC(arg1);
            ec();
          }
          aa("jumpstd")
          {
            vlog("JUMPSTD\r\n",9);
            arg1=GetNum("JUMPSTD");
            if(!gffs){return;}
            BASIC(CMD_JUMPSTD);
            BASIC(arg1);
            ec();
          }
          aa("if")
          {
            vlog("IF\r\n",4);
            arg1=GetNum("IF");
            if(!gffs){return;}
            while(chr==' '){i++;}
            j=0;
            while(chr!=' ')
            {
              buf[j]=chr;
              i++;
              j++;
            }
            buf[j]=0;
            if(!strcmp(buf,"jump")||!strcmp(buf,"goto"))
            {
              vlog("   -> JUMP\r\n",12);
              arg2=GetNum("IF (JUMP)");
              if(!gffs){return;}
              if((arg2&0xff000000)==0)
              {
                arg2|=0x08000000;
                sprintf(buf3,"   -> Converted to 0x%x\r\n",arg2);
                vlog(buf3,strlen(buf3));
              }
              BASIC(CMD_JUMPIF);
            }
            else if(!strcmp(buf,"call"))
            {
              vlog("   -> CALL\r\n",12);
              arg2=GetNum("IF (CALL)");
              if(!gffs){return;}
              if((arg2&0xff000000)==0)
              {
                arg2|=0x08000000;
                sprintf(buf3,"   -> Converted to 0x%x\r\n",arg2);
                vlog(buf3,strlen(buf3));
              }
              BASIC(CMD_CALLIF);
            }
            else
            {
              log("IF was not correctly used. Use if xx JUMP or if xx CALL.\r\n",58);
              return;
            }
            BASIC(arg1);
            rom(arg2,4);
            ec();
          }
          aa("writebytetooffset")
          {
            vlog("   -> WRITEBYTETOOFFSET\r\n",25);
            arg1=GetNum("WRITEBYTETOOFFSET");
            if(!gffs){return;}
            arg2=GetNum("WRITEBYTETOOFFSET");
            if(!gffs){return;}
            BASIC(CMD_WRITEBYTETOOFFSET);
            rom(arg1,1);
            rom(arg2,4);
            ec();
          }
          aa("loadbytefrompointer")
          {
            vlog("   -> LOADBYTEFROMPOINTER\r\n",25);
            arg1=GetNum("LOADBYTEFROMPOINTER");
            if(!gffs){return;}
            arg2=GetNum("LOADBYTEFROMPOINTER");
            if(!gffs){return;}
            BASIC(CMD_LOADBYTEFROMPOINTER);
            rom(arg1,1);
            rom(arg2,4);
            ec();
          }
          aa("special")
          {
            vlog("SPECIAL\r\n",9);
            arg1=GetNum("SPECIAL");
            if(!gffs){return;}
            BASIC(CMD_SPECIAL);
            rom(arg1,2);
            ec();
          }
          aa("special2")
          {
            vlog("SPECIAL2\r\n",10);
            arg1=GetNum("SPECIAL2");
            if(!gffs){return;}
            arg2=GetNum("SPECIAL2");
            if(!gffs){return;}
            BASIC(CMD_SPECIAL2);
            rom(arg1,2);
            rom(arg2,2);
            ec();
          }
          aa("compare")
          {
            vlog("COMPARE\r\n",9);
            arg1=GetNum("COMPARE");
            if(!gffs){return;}
            arg2=GetNum("COMPARE");
            if(!gffs){return;}
            BASIC(CMD_COMPARE);
            rom(arg1,2);
            rom(arg2,2);
            ec();
          }
          aa("copyvar")
          {
            vlog("COPYVAR\r\n",9);
            arg1=GetNum("COPYVAR");
            if(!gffs){return;}
            arg2=GetNum("COPYVAR");
            if(!gffs){return;}
            BASIC(CMD_COPYVAR);
            rom(arg1,2);
            rom(arg2,2);
            ec();
          }
          aa("copyvarifnotzero")
          {
            vlog("COPYVARIFNOTZERO\r\n",18);
            arg1=GetNum("COPYVARIFNOTZERO");
            if(!gffs){return;}
            arg2=GetNum("COPYVARIFNOTZERO");
            if(!gffs){return;}
            BASIC(CMD_COPYVARIFNOTZERO);
            rom(arg1,2);
            rom(arg2,2);
            ec();
          }
          aa("message")
          {
            vlog("MESSAGE\r\n",9);
            arg1=GetNum("MESSAGE");
            if(!gffs){return;}
            BASIC(CMD_MESSAGE);
            if((arg1&0xff000000)==0)
            {
              arg1|=0x08000000;
              sprintf(buf3,"   -> Converted to 0x%x\r\n",arg1);
              vlog(buf3,strlen(buf3));
            }
            rom(arg1,4);
            ec();
          }
          aa("copyscriptbanks")
          {
            vlog("COPYSCRIPTBANKS\r\n",17);
            arg1=GetNum("COPYSCRIPTBANKS");
            if(!gffs){return;}
            arg2=GetNum("COPYSCRIPTBANKS");
            if(!gffs){return;}
            BASIC(CMD_COPYSCRIPTBANKS);
            rom(arg1,1);
            rom(arg2,1);
            ec();
          }
          aa("copybyte")
          {
            vlog("COPYBYTE\r\n",10);
            arg1=GetNum("COPYBYTE");
            if(!gffs){return;}
            arg2=GetNum("COPYBYTE");
            if(!gffs){return;}
            BASIC(CMD_COPYBYTE);
            rom(arg1,4);
            rom(arg2,4);
            ec();
          }
          aa("setvar")
          {
            vlog("SETVAR\r\n",8);
            arg1=GetNum("SETVAR");
            if(!gffs){return;}
            arg2=GetNum("SETVAR");
            if(!gffs){return;}
            BASIC(CMD_SETVAR);
            rom(arg1,2);
            rom(arg2,2);
            ec();
          }
          aa("comparevartobyte")
          {
            vlog("COMPAREVARTOBYTE\r\n",18);
            arg1=GetNum("COMPAREVARTOBYTE");
            if(!gffs){return;}
            arg2=GetNum("COMPAREVARTOBYTE");
            if(!gffs){return;}
            BASIC(CMD_COMPAREVARTOBYTE);
            rom(arg1,2);
            rom(arg2,1);
            ec();
          }
          aa("comparevartofarbyte")
          {
            vlog("COMPAREVARTOFARBYTE\r\n",21);
            arg1=GetNum("COMPAREVARTOFARBYTE");
            if(!gffs){return;}
            arg2=GetNum("COMPAREVARTOFARBYTE");
            if(!gffs){return;}
            BASIC(CMD_COMPAREVARTOFARBYTE);
            rom(arg1,2);
            rom(arg2,4);
            ec();
          }
          aa("comparefarbytetovar")
          {
            vlog("COMPAREFARBYTETOVAR\r\n",21);
            arg1=GetNum("COMPAREFARBYTETOVAR");
            if(!gffs){return;}
            arg2=GetNum("COMPAREFARBYTETOVAR");
            if(!gffs){return;}
            BASIC(CMD_COMPAREFARBYTETOVAR);
            rom(arg1,4);
            rom(arg2,2);
            ec();
          }
          aa("comparefarbytetobyte")
          {
            vlog("COMPAREFARBYTETOBYTE\r\n",22);
            arg1=GetNum("COMPAREFARBYTETOBYTE");
            if(!gffs){return;}
            arg2=GetNum("COMPAREFARBYTETOBYTE");
            if(!gffs){return;}
            BASIC(CMD_COMPAREFARBYTETOBYTE);
            rom(arg1,4);
            rom(arg2,1);
            ec();
          }
          aa("comparefarbytetofarbyte")
          {
            vlog("COMPAREFARBYTETOFARBYTE\r\n",25);
            arg1=GetNum("COMPAREFARBYTETOFARBYTE");
            if(!gffs){return;}
            arg2=GetNum("COMPAREFARBYTETOFARBYTE");
            if(!gffs){return;}
            BASIC(CMD_COMPAREFARBYTETOFARBYTE);
            rom(arg1,4);
            rom(arg2,4);
            ec();
          }
          aa("fadescreen")
          {
            vlog("FADESCREEN\r\n",12);
            arg1=GetNum("FADESCREEN");
            if(!gffs){return;}
            BASIC(CMD_FADESCREEN);
            rom(arg1,1);
            ec();
          }
          aa("callasm")
          {
            vlog("CALLASM\r\n",9);
            arg1=GetNum("CALLASM");
            if(!gffs){return;}
            BASIC(CMD_CALLASM);
            if((arg1&0xff000000)==0)
            {
              arg1|=0x08000000;
              sprintf(buf3,"   -> Converted to 0x%x\r\n",arg1);
              vlog(buf3,strlen(buf3));
            }
            rom(arg1,4);
            ec();
          }
          aa("pause")
          {
            vlog("PAUSE\r\n",7);
            arg1=GetNum("PAUSE");
            if(!gffs){return;}
            BASIC(CMD_PAUSE);
            rom(arg1,2);
            ec();
          }
          aa("setflag")
          {
            vlog("SETFLAG\r\n",9);
            arg1=GetNum("SETFLAG");
            if(!gffs){return;}
            BASIC(CMD_SETFLAG);
            rom(arg1,2);
            ec();
          }
          aa("clearflag")
          {
            vlog("CLEARFLAG\r\n",11);
            arg1=GetNum("CLEARFLAG");
            if(!gffs){return;}
            BASIC(CMD_CLEARFLAG);
            rom(arg1,2);
            ec();
          }
          aa("checkflag")
          {
            vlog("CHECKFLAG\r\n",11);
            arg1=GetNum("CHECKFLAG");
            if(!gffs){return;}
            BASIC(CMD_CHECKFLAG);
            rom(arg1,2);
            ec();
          }
          aa("cmd_2f")  //Remember everything is turned lowercase ...
          {
            vlog("CMD_2F\r\n",8);
            arg1=GetNum("CMD_2F");
            if(!gffs){return;}
            BASIC(CMD_2F);
            rom(arg1,2);
            ec();
          }
          aa("cry")
          {
            vlog("CRY\r\n",5);
            arg1=GetNum("CRY");
            if(!gffs){return;}
            arg2=GetNum("CRY");
            if(!gffs){return;}
            BASIC(CMD_CRY);
            rom(arg1,1);
            rom(arg2,2);
            ec();
          }
          aa("fanfare")
          {
            vlog("FANFARE\r\n",9);
            arg1=GetNum("FANFARE");
            if(!gffs){return;}
            BASIC(CMD_FANFARE);
            rom(arg1,2);
            ec();
          }
          aa("playsound")
          {
            vlog("PLAYSOUND\r\n",11);
            arg1=GetNum("PLAYSOUND");
            if(!gffs){return;}
            BASIC(CMD_PLAYSOUND);
            rom(arg1,2);
            ec();
          }
          aa("fadesound")
          {
            vlog("FADESOUND\r\n",11);
            arg1=GetNum("FADESOUND");
            if(!gffs){return;}
            BASIC(CMD_FADESOUND);
            rom(arg1,2);
            ec();
          }
          aa("cmd_c3")
          {
            vlog("CMD_C3\r\n",8);
            arg1=GetNum("CMD_C3");
            if(!gffs){return;}
            BASIC(CMD_C3);
            rom(arg1,1);
            ec();
          }
          aa("warp")
          {
            vlog("WARP\r\n",6);
            arg1=GetNum("WARP");
            if(!gffs){return;}
            arg2=GetNum("WARP");
            if(!gffs){return;}
            arg3=GetNum("WARP");
            if(!gffs){return;}
            BASIC(CMD_WARP);
            rom(arg1,1);
            rom(arg2,1);
            rom(arg3,1);
            ec();
          }
          aa("removeitem")
          {
            vlog("REMOVEITEM\r\n",12);
            arg1=GetNum("REMOVEITEM");
            if(!gffs){return;}
            arg2=GetNum("REMOVEITEM");
            if(!gffs){return;}
            BASIC(CMD_REMOVEITEM);
            rom(arg1,2);
            rom(arg2,2);
            ec();
          }
          aa("checkitem")
          {
            vlog("CHECKITEM\r\n",11);
            arg1=GetNum("CHECKITEM");
            if(!gffs){return;}
            arg2=GetNum("CHECKITEM");
            if(!gffs){return;}
            BASIC(CMD_CHECKITEM);
            rom(arg1,2);
            rom(arg2,2);
            ec();
          }
          aa("applymovement")
          {
            vlog("APPLYMOVEMENT\r\n",15);
            arg1=GetNum("APPLYMOVEMENT");
            if(!gffs){return;}
            arg2=GetNum("APPLYMOVEMENT");
            if(!gffs){return;}
            BASIC(CMD_APPLYMOVEMENT);
            rom(arg1,2);
            rom(arg2,4);
            ec();
          }
          aa("pauseevent")
          {
            vlog("PAUSEEVENT\r\n",12);
            arg1=GetNum("PAUSEEVENT");
            if(!gffs){return;}
            BASIC(CMD_PAUSEEVENT);
            rom(arg1,2);
            ec();
          }
          aa("trainerbattle")
          {
            vlog("TRAINERBATTLE\r\n",15);
            arg1=GetNum("TRAINERBATTLE");
            if(!gffs){return;}
            arg2=GetNum("TRAINERBATTLE");
            if(!gffs){return;}
            arg3=GetNum("TRAINERBATTLE");
            if(!gffs){return;}
            arg4=GetNum("TRAINERBATTLE");
            if(!gffs){return;}
            arg5=GetNum("TRAINERBATTLE");
            if(!gffs){return;}
            BASIC(CMD_TRAINERBATTLE);
            rom(arg1,1);
            rom(arg2,2);
            rom(arg3,2);
            rom(arg4,4);
            rom(arg5,4);
            if(arg1==1)
            {
              arg6=GetNum("TRAINERBATTLE");
              if(!gffs){return;}
              rom(arg6,4);
            }
            ec();
          }
          aa("multichoice")
          {
            vlog("MULTICHOICE\r\n",13);
            arg1=GetNum("MULTICHOICE");
            if(!gffs){return;}
            arg2=GetNum("MULTICHOICE");
            if(!gffs){return;}
            arg3=GetNum("MULTICHOICE");
            if(!gffs){return;}
            arg4=GetNum("MULTICHOICE");
            if(!gffs){return;}
            BASIC(CMD_MULTICHOICE);
            rom(arg1,1);
            rom(arg2,1);
            rom(arg3,1);
            rom(arg4,1);
            ec();
          }
          aa("picture")
          {
            vlog("PICTURE\r\n",9);
            arg1=GetNum("PICTURE");
            if(!gffs){return;} //GFFS stands for Get-For-Function success. GetNum sets this to 0 on failure.
            BASIC(CMD_PICTURE);
            rom(arg1,1);
            ec();
          }
          aa("braille")
          {
            vlog("BRAILLE\r\n",9);
            arg1=GetNum("BRAILLE");
            if(!gffs){return;}
            BASIC(CMD_BRAILLE);
            if((arg1&0xff000000)==0)
            {
              arg1|=0x08000000;
              sprintf(buf3,"   -> Converted to 0x%x\r\n",arg1);
              vlog(buf3,strlen(buf3));
            }
            rom(arg1,4);
            ec();
          }
          aa("cmd_d3")
          {
            vlog("CMD_D3\r\n",8);
            arg1=GetNum("CMD_D3");
            if(!gffs){return;}
            BASIC(CMD_D3);
            rom(arg1,4);
            ec();
          }
          aa("cmd_fb")
          {
            vlog("CMD_FB\r\n",8);
            arg1=GetNum("CMD_FB");
            if(!gffs){return;}
            BASIC(CMD_FB);
            rom(arg1,4);
            ec();
          }
          aa("addpokemon")
          {
            vlog("ADDPOKEMON\r\n",12);
            arg1=GetNum("ADDPOKEMON");
            if(!gffs){return;}
            arg2=GetNum("ADDPOKEMON");
            if(!gffs){return;}
            arg3=GetNum("ADDPOKEMON");
            if(!gffs){return;}
            BASIC(CMD_ADDPOKEMON);
            rom(arg1,2);
            rom(arg2,1);
            rom(arg3,2);
            ec();
          }
          aa("storepokemon")
          {
            vlog("STOREPOKEMON\r\n",14);
            arg1=GetNum("STOREPOKEMON");
            if(!gffs){return;}
            arg2=GetNum("STOREPOKEMON");
            if(!gffs){return;}
            BASIC(CMD_STOREPOKEMON);
            rom(arg1,1);
            rom(arg2,2);
            ec();
          }
          aa("storevar")
          {
            vlog("STOREVAR\r\n",10);
            arg1=GetNum("STOREVAR");
            if(!gffs){return;}
            arg2=GetNum("STOREVAR");
            if(!gffs){return;}
            BASIC(CMD_STOREVAR);
            rom(arg1,1);
            rom(arg2,2);
            ec();
          }
          aa("storetext")
          {
            vlog("STORETEXT\r\n",11);
            arg1=GetNum("STORETEXT");
            if(!gffs){return;}
            arg2=GetNum("STORETEXT");
            if(!gffs){return;}
            BASIC(CMD_STORETEXT);
            rom(arg1,1);
            if((arg2&0xff000000)==0)
            {
              arg2|=0x08000000;
              sprintf(buf3,"   -> Converted to 0x%x\r\n",arg2);
              vlog(buf3,strlen(buf3));
            }
            rom(arg2,4);
            ec();
          }
          aa("pokemart")
          {
            vlog("POKEMART\r\n",10);
            arg1=GetNum("POKEMART");
            if(!gffs){return;}
            BASIC(CMD_POKEMART);
            rom(arg1,4);
            ec();
          }
          aa("setmaptile")
          {
            vlog("SETMAPTILE\r\n",12);
            arg1=GetNum("SETMAPTILE");
            if(!gffs){return;}
            arg2=GetNum("SETMAPTILE");
            if(!gffs){return;}
            arg3=GetNum("SETMAPTILE");
            if(!gffs){return;}
            arg4=GetNum("SETMAPTILE");
            if(!gffs){return;}
            BASIC(CMD_SETMAPTILE);
            rom(arg1,2);
            rom(arg2,2);
            rom(arg3,2);
            rom(arg4,2);
            ec();
          }
          aa("setweather")
          {
            vlog("SETWEATHER\r\n",12);
            arg1=GetNum("SETWEATHER");
            if(!gffs){return;}
            BASIC(CMD_SETWEATHER);
            rom(arg1,1);
            ec();
          }
          aa("battle")
          {
            vlog("BATTLE\r\n",8);
            arg1=GetNum("BATTLE");
            if(!gffs){return;}
            arg2=GetNum("BATTLE");
            if(!gffs){return;}
            arg3=GetNum("BATTLE");
            if(!gffs){return;}
            BASIC(CMD_BATTLE);
            rom(arg1,2);
            rom(arg2,1);
            rom(arg3,2);
            ec();
          }
          aa("cmd_73")
          {
            vlog("CMD_73\r\n",8);
            arg1=GetNum("CMD_73");
            if(!gffs){return;}
            arg2=GetNum("CMD_73");
            if(!gffs){return;}
            BASIC(CMD_73);
            rom(arg1,2);
            rom(arg2,2);
            ec();
          }
          aa("storeitem")
          {
            vlog("STOREITEM\r\n",11);
            arg1=GetNum("STOREITEM");
            if(!gffs){return;}
            arg2=GetNum("STOREITEM");
            if(!gffs){return;}
            BASIC(CMD_STOREITEM);
            rom(arg1,1);
            rom(arg2,2);
            ec();
          }
          aa("storeatk")
          {
            vlog("STOREATK\r\n",10);
            arg1=GetNum("STOREATK");
            if(!gffs){return;}
            arg2=GetNum("STOREATK");
            if(!gffs){return;}
            BASIC(CMD_STOREATK);
            rom(arg1,1);
            rom(arg2,2);
            ec();
          }
          aa("storefurniture")
          {
            vlog("STOREFURNITURE\r\n",16);
            arg1=GetNum("STOREFURNITURE");
            if(!gffs){return;}
            arg2=GetNum("STOREFURNITURE");
            if(!gffs){return;}
            BASIC(CMD_STOREFURNITURE);
            rom(arg1,1);
            rom(arg2,2);
            ec();
          }
          aa("storecomp")
          {
            vlog("STORECOMP\r\n",11);
            arg1=GetNum("STORECOMP");
            if(!gffs){return;}
            arg2=GetNum("STORECOMP");
            if(!gffs){return;}
            BASIC(CMD_STORECOMP);
            rom(arg1,1);
            rom(arg2,2);
            ec();
          }
          aa("cmd_9d")
          {
            vlog("CMD_9D\r\n",8);
            arg1=GetNum("CMD_9D");
            if(!gffs){return;}
            arg2=GetNum("CMD_9D");
            if(!gffs){return;}
            BASIC(CMD_9D);
            rom(arg1,2);
            rom(arg2,1);
            ec();
          }
          aa("namepokemon")
          {
            BASIC(CMD_FADESCREEN);
            BASIC(1);
            BASIC(CMD_SPECIAL);
            rom(0x9E,2);
            BASIC(CMD_WAITSPECIAL);
            ec();
          }
          aa("slotmachine")
          {
            vlog("SLOTMACHINE\r\n",13);
            arg1=GetNum("SLOTMACHINE");
            if(!gffs){return;}
            BASIC(CMD_SLOTMACHINE);
            rom(arg1,2);
            ec();
          }
          aa("giveegg")
          {
            vlog("GIVEEGG\r\n",9);
            arg1=GetNum("GIVEEGG");
            if(!gffs){return;}
            BASIC(CMD_GIVEEGG);
            rom(arg1,2);
            ec();
          }
          aa("disappear")
          {
            vlog("DISAPPEAR\r\n",11);
            arg1=GetNum("DISAPPEAR");
            if(!gffs){return;}
            BASIC(CMD_DISAPPEAR);
            rom(arg1,2);
            ec();
          }
          aa("cmd_93")
          {
            vlog("CMD_93\r\n",8);
            arg1=GetNum("CMD_93");
            if(!gffs){return;}
            arg2=GetNum("CMD_93");
            if(!gffs){return;}
            BASIC(CMD_93);
            rom(arg1,2);
            rom(arg2,1);
            ec();
          }
          aa("multichoice2")
          {
            vlog("MULTICHOICE2\r\n",8);
            arg1=GetNum("MULTICHOICE2");
            if(!gffs){return;}
            arg2=GetNum("MULTICHOICE2");
            if(!gffs){return;}
            arg3=GetNum("MULTICHOICE2");
            if(!gffs){return;}
            arg4=GetNum("MULTICHOICE2");
            if(!gffs){return;}
            BASIC(CMD_MULTICHOICE2);
            rom(arg1,1);
            rom(arg2,1);
            rom(arg3,1);
            rom(arg4,2);
            ec();
          }
          aa("cmd_c1")
          {
            vlog("CMD_C1\r\n",8);
            arg1=GetNum("CMD_C1");
            if(!gffs){return;}
            BASIC(CMD_C1);
            rom(arg1,2);
            ec();
          }
          aa("cmd_c0")
          {
            vlog("CMD_C0\r\n",8);
            arg1=GetNum("CMD_C0");
            if(!gffs){return;}
            BASIC(CMD_C0);
            rom(arg1,2);
            ec();
          }
          aa("cmd_94")
          {
            vlog("CMD_94\r\n",8);
            arg1=GetNum("CMD_94");
            if(!gffs){return;}
            BASIC(CMD_94);
            rom(arg1,2);
            ec();
          }
          aa("coincasetovar")
          {
            vlog("CoinCaseToVar\r\n",15);
            arg1=GetNum("COINCASETOVAR");
            if(!gffs){return;}
            BASIC(CMD_COINCASETOVAR);
            rom(arg1,2);
            ec();
          }
          aa("givetocoincase")
          {
            vlog("GIVETOCOINCASE\r\n",16);
            arg1=GetNum("GIVETOCOINCASE");
            if(!gffs){return;}
            BASIC(CMD_GIVETOCOINCASE);
            rom(arg1,2);
            ec();
          }
          aa("cmd_95")
          {
            vlog("CMD_95\r\n",8);
            arg1=GetNum("CMD_95");
            if(!gffs){return;}
            arg2=GetNum("CMD_95");
            if(!gffs){return;}
            BASIC(CMD_95);
            rom(arg1,1);
            rom(arg2,2);
            ec();
          }
          aa("cmd_92")
          {
            vlog("CMD_92\r\n",8);
            arg1=GetNum("CMD_92");
            if(!gffs){return;}
            arg2=GetNum("CMD_92");
            if(!gffs){return;}
            arg2=GetNum("CMD_92");
            if(!gffs){return;}
            BASIC(CMD_95);
            rom(arg1,1);
            rom(arg2,2);
            rom(arg3,2);
            ec();
          }
          aa("cmd_91")
          {
            vlog("CMD_91\r\n",8);
            arg1=GetNum("CMD_91");
            if(!gffs){return;}
            arg2=GetNum("CMD_91");
            if(!gffs){return;}
            arg2=GetNum("CMD_91");
            if(!gffs){return;}
            BASIC(CMD_95);
            rom(arg1,1);
            rom(arg2,2);
            rom(arg3,2);
            ec();
          }
          aa("cmd_96")
          {
            vlog("CMD_96\r\n",8);
            arg1=GetNum("CMD_96");
            if(!gffs){return;}
            BASIC(CMD_96);
            rom(arg1,2);
            ec();
          }
          aa("cmd_17")
          {
            vlog("CMD_17\r\n",8);
            arg1=GetNum("CMD_17");
            if(!gffs){return;}
            arg2=GetNum("CMD_17");
            if(!gffs){return;}
            BASIC(CMD_17);
            rom(arg1,2);
            rom(arg2,2);
            ec();
          }
          aa("cmd_fe")
          {
            vlog("CMD_FE\r\n",8);
            arg1=GetNum("CMD_FE");
            if(!gffs){return;}
            BASIC(CMD_FE);
            rom(arg1,1);
            ec();
          }
          aa("cmd_61")
          {
            vlog("CMD_61\r\n",8);
            arg1=GetNum("CMD_61");
            if(!gffs){return;}
            BASIC(CMD_61);
            rom(arg1,2);
            ec();
          }
          aa("cmd_22")
          {
            vlog("CMD_22\r\n",8);
            arg1=GetNum("CMD_22");
            if(!gffs){return;}
            arg2=GetNum("CMD_22");
            if(!gffs){return;}
            BASIC(CMD_22);
            rom(arg1,2);
            rom(arg2,2);
            ec();
          }
          aa("cmd_c7")
          {
            vlog("CMD_C7\r\n",8);
            arg1=GetNum("CMD_C7");
            if(!gffs){return;}
            BASIC(CMD_C7);
            rom(arg1,1);
            ec();
          }
          aa("=")
          {
            vlog("[STRING]\r\n",10);
            if(chr==' '){i++;}
            else{log("Should have a space after the =\r\n",33);}
            temp_ptr=transbackstr(script,i-SetFilePointer(IncFile,0,NULL,FILE_END)-1,RomFile);
            while(chr!='\n'&&chr!=0){i++;}
            sprintf(buf2,"   -> %s\r\n",temp_ptr);
            //Spidey sense : Incoming memory leak...
            GlobalFree(temp_ptr);
            //Disaster averted.
            vlog(buf2,strlen(buf2));
          }
          aa(".")
          {
            vlog("[BINARY]\r\n   ->",15);
            while(chr==' '){i++;}
            k=0;
            while(chr!='\n'&&chr!=0)
            {
              k=1-k;
              while(chr==' ')
              {i++;}
              j=0;
              while(((char*)("0123456789abcdef"))[j]!=0)
              {
                if(((char*)("0123456789abcdef"))[j]==chr)
                {
                  break;
                }
                j+=1;
              }
              if(((char*)("0123456789abcdef"))[j]==0)
              {
                sprintf(buf2,"Failed to understand hex character '%c'\r\n",chr);
                log(buf2,strlen(buf2));
                return;
              }
              if(k==0)
              {
                l|=j;
                rom(j,1);
                if(IsVerbose)
                {
                  sprintf(buf2," %02X",l);
                  log(buf2,strlen(buf2));
                }
              }
              else
              {
                l=j<<4;
              }
              i++;
            }
            vlog("\r\n",2);
          }
          else
          {
            sprintf(buf2,"Warning: Unknown command \"%s\"\r\n",buf);
            log(buf2,strlen(buf2));
            while(chr!='\n'&&chr!=0)
            {
              i++;
            }
          }
          break;
      }
      i++;
    }
    ///WriteFile(LogFile,stuff,fs,&read,NULL);
    GlobalFree(Script);
    CloseHandle(LogFile);
    CloseHandle(IncFile);
    if(strcmp(script,""))CloseHandle(CurrFile);
  }
  else
  {
    printf("Error opening script.");
    return;
  }
  return;
}
